### ISSUE TITLE
Lock player weapons when ping is too high

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1021]

**Comment by QuentinGruber** [comment]
Await #1099

**Comment by Z1Meme** [comment]
@QuentinGruber @avcio9 Is this already implemented?

**Comment by QuentinGruber** [comment]
> @QuentinGruber @avcio9 Is this already implemented?

Well this is easy to do and i've made it on a PR if i remember well, but since my ping calculation is shitty :( i'm not enabling that.

**Comment by QuentinGruber** [comment]
https://github.com/QuentinGruber/h1z1-server/pull/1098 idk what to do with the possible timedrifts and so on, maybe player ping is sent by the client via clientMetrics but goodluck to find it in this. Since the client is the one doing a full sync with the server would make sense that he know his ping.

**Comment by QuentinGruber** [comment]
Will implement this when we reopen community servers registration for regions we don't host ( it won't be fair to unallow these people to play )

**Comment by QuentinGruber** [comment]
https://github.com/QuentinGruber/h1z1-server/pull/1355 ping lock instead
