### ISSUE TITLE
Hello, dear h1emu development team  I am a h1z1 Chinese player I hope to join your development team to make h1emu better and better  What can I bring you?  1: I am a college student majoring in computer science. I will actively help you collect suggestions from Chinese Forum players  2: I can master the practical Java web framework to support the future needs of the team  3: I master the basic use of Linux shell, and can accurately locate the problems and solutions of h1emu in operation  4: I have enough time    Please let me help h1emu thank you

### ISSUE THREAD

**Issue by Corybyte** [QuentinGruber/h1z1-server#1033]
Hello, dear h1emu development team

I am a h1z1 Chinese player I hope to join your development team to make h1emu better and better

What can I bring you?

1: I am a college student majoring in computer science. I will actively help you collect suggestions from Chinese Forum players

2: I can master the practical Java web framework to support the future needs of the team

3: I master the basic use of Linux shell, and can accurately locate the problems and solutions of h1emu in operation

4: I have enough time

Please let me help h1emu thank you

**Comment by QuentinGruber** [comment]
Contact Kentin#7587 or Meme#2744 on discord thx ! 😃

**Comment by Corybyte** [comment]
I made a friend request

**Comment by Corybyte** [comment]
> 在 discord thx 上联系 Kentin#7587 或 Meme#2744！😃

I made a friend request
