### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by BigChubs** [QuentinGruber/h1z1-server#1034]
On 7/24/2022 I notice the following bugs.

1. I can't equipe shoes if they are in my backpack. If I drop the shoes that I am wearing. Then pick up new pair of shoes. They will automatically equipe. 
2. When trying to use fist or melee weapons as my primary weapon. It dosn't do anything. No movment on screen or damage. 
3. I can also run through zombies and zombies just don't notice that I am there. 

I just started playing this game couple days before this. And I played it a lot when Daybreak had it up. Thanks for bringing it back alive. I hope this helps you guys out. Sorry if these bugs have already been reported. 

Hope you guys had a great day!

Running h1emu version 0.21.0 with latest Game files through launcher
Windows 11 Home
OS build 22000.795
12 Gen Intel i5-12400F 2.5
32 GB Ram
Asus Geforce RTX 3050

**Comment by QuentinGruber** [comment]
Hey @BigChubs thanks for your report, issues 2 & 3 are just work in progress so it's not really a bug, but 1) is one I will reference in a new issue gh 🤠

**Comment by QuentinGruber** [comment]
I can't equipe shoes if they are in my backpack. If I drop the shoes that I am wearing. Then pick up new pair of shoes. They will automatically equipe.
