### ISSUE TITLE
I can't equip shoes if they are in my backpack.

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1035]
I can't equipe shoes if they are in my backpack. If I drop the shoes that I am wearing. Then pick up new pair of shoes. They will automatically equipe.

_Originally posted by @QuentinGruber in https://github.com/QuentinGruber/h1z1-server/issues/1034#issuecomment-1200845603_

**Comment by Z1Meme** [comment]
Can't reproduce, convey equipping works fine.
