### ISSUE TITLE
Validation functions for pvp / movement

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1046]
Player movement and hit registration should have a function at the top like "validate movement" or "validate hit" that goes through a series of small checks to make sure that gameplay is fair.
Ex. check if player is moving to fast (speedhack) and negate it, check if player is attempting to shoot with an empty clip / shooting too quickly (ex. Full auto .308) etc.

**Comment by Z1Meme** [comment]
This should be included https://github.com/QuentinGruber/h1z1-server/issues/1021

**Comment by QuentinGruber** [comment]
Kinda done on #1076
