### ISSUE TITLE
Server config file

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1057]
Add a config file that is set as an env var ex: `--env CONFIG="./config.json"`, server should include a default config template that can be copied / edited

**Comment by QuentinGruber** [comment]
Also the config file vars should be store as env value at h1z1-server start. So you can use standalone env vars or just setup a whole config file. ( we could have a small function running at h1z1-server.js )

**Comment by QuentinGruber** [comment]
Maybe the config file could be even used as an argument ? Can be even easier
