### ISSUE TITLE
extremely low y axis on positionupdate sometimes

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1068]
PlayerUpdatePosition : {"transientId":30730,"positionUpdate":{"flags":510,"sequenceTime":1691403339,"unknown3_int8":0,"position":[74.7,-2767523.2,-942.91],"orientation":3.0199999809265137,"frontTilt":0,"sideTilt":0,"angleChange":-2.92,"verticalSpeed":-1.57,"horizontalSpeed":1298.1,"unknown12_float":[0,0,0]}}

Have noticed this log on my server from time to time, not sure how to reproduce this.

**Comment by QuentinGruber** [comment]
probably a vehicle that falls through the map? We should just make it so that when something falls in the negative we reset the pos Y has 20 or so.
