### ISSUE TITLE
Custom h1emu packets / clientside handler

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1070]
Would be implemented in both the server and patch to be able to implement extra client features, such as being able to refresh the server list by typing "refresh" into the console, sending a kick message to the client on the server menu, etc.

**Comment by Z1Meme** [comment]
Would also allow us to put the combatlog in the console only, rather than both the console and the chat, as well as an actual acurate on-demand "ping" command.

**Comment by Z1Meme** [comment]
@QuentinGruber Thoughts?

**Comment by Z1Meme** [comment]
We would either have to figure out how to utilize the internal h1z1 packet sending functions (which could potentially create a security issue), or create our own which would create another connection to the zoneserver which only interacts with our custom clientside handler.

**Comment by Z1Meme** [comment]
This would also allow us to get custom assets to the client, such as locale strings, textures, maps, etc. (This would be for the future)

**Comment by QuentinGruber** [comment]
> @QuentinGruber Thoughts?

To be honest, it seems like too much for me, we are here to emulate and not to modify as much, but that's only my opinion.

**Comment by Z1Meme** [comment]
> > @QuentinGruber Thoughts?
> 
> To be honest, it seems like too much for me, we are here to emulate and not to modify as much, but that's only my opinion.

Well this would mainly be for QOL type things, such as only showing the combatlog in console, instead of chat, and showing a kick message after you're kicked. We could also edit the in-game strings for custom server names on the fly when the client loads, instead of overwriting the actual file itself.

**Comment by QuentinGruber** [comment]
> > > @QuentinGruber Thoughts?
> > 
> > 
> > To be honest, it seems like too much for me, we are here to emulate and not to modify as much, but that's only my opinion.
> 
> Well this would mainly be for QOL type things, such as only showing the combatlog in console, instead of chat, and showing a kick message after you're kicked. We could also edit the in-game strings for custom server names on the fly when the client loads, instead of overwriting the actual file itself.

About the combatlog, isn't it already possible to do this via channels in chat messages? Also for the kick message, there are some possible workarounds without much trouble. Personally, I don't see a problem with overwriting the current file (for strings). To me, the game should be able to run and function on our servers without modifying the binary file. Also, this client-side handler could cause problems that would be difficult to debug. I'm not closed to the idea of having one, just at the moment I don't really see the point of it without it being overkill
