### ISSUE TITLE
Transfer protocol between soeserver and udpserver

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1096]

**Comment by Z1Meme** [comment]
Whats the purpose of this exactly?

**Comment by QuentinGruber** [comment]
> Whats the purpose of this exactly?

Currently the data between the main thread and the udp server thread is copied, there are ways to transfer data between threads that are a cheaper operation than copying (this copying happens every time a physical packet is sent, so it makes sense for me to try to optimize this). The word "protocol" is probably not the right one for this, I didn't know what to call it 😅, I'll show you in the PR I'll do.

**Comment by QuentinGruber** [comment]
should do #1095 first to test that
