### ISSUE TITLE
Zombies equipment don't always show up at first look

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1150]

**Comment by Z1Meme** [comment]
https://github.com/QuentinGruber/h1z1-server/issues/1024

**Comment by Z1Meme** [comment]
@QuentinGruber is this even still an issue?

**Comment by QuentinGruber** [comment]
> @QuentinGruber is this even still an issue?

I believe so, happenned to me again like a week ago i believe

**Comment by Z1Meme** [comment]
should send SetEquipment packet for npc on FullDataRequest if we aren't already

**Comment by Z1Meme** [comment]
Can't reproduce and this pr is stale
