### ISSUE TITLE
ak47 replication issue 

### ISSUE THREAD

**Issue by coderuk** [QuentinGruber/h1z1-server#1159]
The ak47 is only being replicated for one client 
**To Reproduce**
Steps to reproduce :
1. Get 2 clients 
2. give each an ak47
3. shoot on each client 
4. replication will only work for one of the clients 
[Video Demo link ](https://discord.com/channels/707525351357677610/1034576665579364403/1048609660334243941)

**Comment by Z1Meme** [comment]
@coderuk is this still broken?
