### ISSUE TITLE
ied explosion causing service restarts and a sharp increase in server cpu and memory usage.

### ISSUE THREAD

**Issue by alvazhang79** [QuentinGruber/h1z1-server#1170]
38 IEDs were placed at once and lit with a fire engine. the ZoneServer of the Docker container restarted. The game saw 20 IEDs left. Then the server cpu and memory usage rises sharply.
Screenshots:
https://cdn.discordapp.com/attachments/853959291131789332/1049515668501958656/image.png
https://cdn.discordapp.com/attachments/853959291131789332/1049515668858470400/image.png

Verified version: 0.22.3

**Comment by Z1Meme** [comment]
Looks like the server gets stuck in an infinite loop trying to send Character.PlayWorldCompositeEffect, it also appears to create a memory leak.

**Comment by Z1Meme** [comment]
Fixed in next release 👍
