### ISSUE TITLE
Unknown SOE Packet 0x05

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1178]
Randomly sent from some clients.
![](https://i.gyazo.com/03b54b95701917a9763fada81ee8cd61.png)
![](https://i.gyazo.com/eef967bd7d864809bd832cb3464c0582.png)

**Comment by QuentinGruber** [comment]
I've just put the wrong size for this packet in h1emu core it seems : https://github.com/H1emu/h1emu-core/blob/main/src/soeprotocol_functions.rs#L9 will fix that
