### ISSUE TITLE
generateRandomGuid generating an already existing guid in extremely rare cases

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1180]
Has not been documented as happening yet, however if this were to occur one entity could either completely overwrite another one, or create weird conflicts that are hard to track. Should make this function recursive and check if the guid is already in use by another entity. Also need to make sure that this system still works on server save / load, and after a restart.

**Comment by QuentinGruber** [comment]
The chances are very very rare and I guess that's the price for a 50ns GUID generation in my opinion.

**Comment by QuentinGruber** [comment]
For me this issue should be closed as not planned, the chances a really too low to care about : there is 18,446,744,073,709,551,615 possible value even if we had 1 million entity spawned at the same time there will still have 1/18,446,744,073,709% chance that a dup GUID is generated. @Z1Meme
