### ISSUE TITLE
logging in problem

### ISSUE THREAD

**Issue by mvmes2** [QuentinGruber/h1z1-server#1193]
**Describe the bug**
when logged in the game, after 5 sec, the game closes and start up the steam version.

**To Reproduce**
1. Go to 'Launcher'
2. Click on 'play'
3. Scroll down to 'any server and enter the server'
4. after 5 sec online, See the error, game closing and opneing steam version

**Expected behavior**
able to play normaly.

**Screenshots**
![image](https://user-images.githubusercontent.com/54598491/210102424-8f3677c8-dff6-4d2e-8f32-e9e83157ffe9.png).

**Additional context**

**Comment by QuentinGruber** [comment]
Wrong repository => https://github.com/H1emu/h1emu-launcher/issues/17
