### ISSUE TITLE
Negative count items causing container packets to fail parsing

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1220]
Somehow items are able to get to negative numbers in a stack and it breaks the container packet parsing.

**Comment by QuentinGruber** [comment]
Is this something we should fix directly in h1z1-dataschema ? Like  negative number in an unsigned type should result to 0? @Z1Meme

**Comment by Z1Meme** [comment]
> Is this something we should fix directly in h1z1-dataschema ? Like  negative number in an unsigned type should result to 0? @Z1Meme 

We can but we need to make it log that it did so since negative number items should never happen. Some item logic is causing stack counts to become negative, that's what needs to be fixed.

**Comment by QuentinGruber** [comment]
It's considered as fixed right ? @Z1Meme
