### ISSUE TITLE
Add loot drop when a npcs is killed

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1234]

**Comment by Z1Meme** [comment]
Should build out this system with basic drops for now in preparation for an actual zombie update at some point. Should also re-create the mechanic where player lootbags that despawn are assigned to newly spawned zombies, so you can kill a zombie for someone's despawned lootbag loot.

**Comment by QuentinGruber** [comment]
Would be cool since we can melee kill them now

**Comment by DaEgo** [comment]
and pls make the loot bag bigger, if i remember correct they changed this size
