### ISSUE TITLE
Item bug error

### ISSUE THREAD

**Issue by WillzinPBS** [QuentinGruber/h1z1-server#1304]
First of all, I would like to congratulate the whole team for the incredible work they are doing, and I would be very happy to get back to playing Just Survive in the most updated version!

I noticed that I am not able to get items from boxes/storages or from the loot of the players that I kill. I imagine you are already aware of this error, but just for the record, and whenever you enter a full server, the game closes automatically.

**Comment by Z1Meme** [comment]
Containers are currently shown on the right side of the inventory, alongside your backpack and shirt. You need to click and drag items to / from containers for now, rather than just clicking on them.
