### ISSUE TITLE
cranberry PD womens bathroom corner walk thru wall

### ISSUE THREAD

**Issue by soschronotek** [QuentinGruber/h1z1-server#1311]
**Describe the bug**
cranberry PD womens bathroom corner walk thru wall from insdie of bathroom behind door

**To Reproduce**
1. Go to into womens bathroom
2. walk behind the entry door
3. can go right thru the wall

**Expected behavior**
wall should stop you

**Screenshots**
![image](https://user-images.githubusercontent.com/18426649/215337868-c1a58786-e30e-49fe-b033-fe39d86b27c8.png)
![image](https://user-images.githubusercontent.com/18426649/215337873-415ee533-6cc7-48f6-b6b1-c68e03c0b75f.png)

**Additional context**

**Comment by QuentinGruber** [comment]
Hey @soschronotek sadly it's a client-side issue, can't do much about it.

**Comment by QuentinGruber** [comment]
We keep the report but it won't be fixed here, maybe if a day we start patching the client, but anyway thanks for the report 🤠

**Comment by soschronotek** [comment]
No worries! Keep up the good work!Sent from my iPhoneOn Jan 29, 2023, at 8:00 AM, Qgruber ***@***.***> wrote:﻿
Hey @soschronotek sadly it's a client-side issue, can't do much about it.
