### ISSUE TITLE
invisible

### ISSUE THREAD

**Issue by Neriss60** [QuentinGruber/h1z1-server#1314]
bonjour, je ne peut pas frapper les zombies et il ne me voit pas. tout les meubles que je fouilles sont vide, la sirène sur la voiture de police ne fonctionne pas

**Comment by QuentinGruber** [comment]
> bonjour, je ne peut pas frapper les zombies et il ne me voit pas. tout les meubles que je fouilles sont vide, la sirène sur la voiture de police ne fonctionne pas

Bonjour, ce ne sont pas des "bug" a proprement parlé mais des fonctionnalités manquante encore en développement.
Et par rapport aux meubles vides: leur stockage s'affiche dans l'inventaire à droite :)
