### ISSUE TITLE
Join Server button does nothing

### ISSUE THREAD

**Issue by kendulinjr** [QuentinGruber/h1z1-server#1319]
When the server selection screen is displayed I am unable to join any server. If I click Join Server on a server I have a character on it does nothing and will eventually close with no error. If I click Join Server on a server which I do not have a character on it will take me to character creation screen. I type in a name and it sits at verifying name message and never completes.

**To Reproduce**
1. Open H1Emu Launcher, click play
2. On server selection screen, select server and click Join Server

**Expected behavior**
Expect to enter selected server

**Screenshots**
N/a

**Additional context**
Everything worked fin 2 days ago, this happens on all servers

**Comment by kendulinjr** [comment]
Looks like getting no reply from server, this is from my router logs:
udp   192.168.1.210:60485                      15.236.188.145:1115                      UNREPLIED

**Comment by QuentinGruber** [comment]
Hey @kendulinjr since none of our deep network code was modified 2 days go it must come from you, maybe we could help you if you send us more data about your: your country, ipv4/ipv5 stuff like that :)

**Comment by QuentinGruber** [comment]
Dupe as #1345
