### ISSUE TITLE
couple of bugs/fixes

### ISSUE THREAD

**Issue by KaoZGaleN** [QuentinGruber/h1z1-server#1331]
Hello, first and foremost i would like to say great job on getting js back, im enjoying it, but it needs a little more to it!

People get invisible sometimes after exiting a vehicle (they can kill you easily as you can neither hear or see them)

Party/group system not working

Need to fix loot system (so you only need to click the items for it to come to ur inventory) mostly while looting peoples lootbags/containers. Also get items to stack when you put them in a container so you dont need to stack everything 1by1.

Vehicle car sound, as soon as a car drives near you and keeps going untill out of render, you can still hear the sound of the car being close to you for about 20-30seconds.

hospital lockers not working (with keys)

windows are not breaking when shot at (cant loot items at apartments that spawns on some balconys because of it)

i'm sure you probably know about most of these and are working on it but i thought i'd type it anyways just incase.

**Comment by KaoZGaleN** [comment]
also vehicles disappearing from your base as soon as server restarts

**Comment by QuentinGruber** [comment]
Hey thx for your report, i will create multiples issues from yours when i have time until you wanna do it yourself 😀 I've already create one for saving vehicules you can create the others if you want and close this one 🤠

**Comment by QuentinGruber** [comment]
https://github.com/QuentinGruber/h1z1-server/issues/1358 https://github.com/QuentinGruber/h1z1-server/issues/1335 https://github.com/QuentinGruber/h1z1-server/issues/1041 https://github.com/QuentinGruber/h1z1-server/issues/1243
