### ISSUE TITLE
Stuck on validating nickname to join server. Cant join any server

### ISSUE THREAD

**Issue by seishes** [QuentinGruber/h1z1-server#1345]
**Describe the bug**
Game launches great but when i try to join any server, i get stuck on the validating name screen. After 1-2 minutes on the waiting name validation screen, i get pushed to the main screen and cant even get to the nickname screen without restarting the game.

**To Reproduce**
1. Go to 'join any server'
2. Click on 'nickname box and type it'
3. Scroll down to 'NOT APLICABLE '

**Expected behavior**
The game would validate my nickname in 15 seconds (3 FRIENDS OF MINE GAMES WORKS LIKE THAT)

**Screenshots**

![Screenshot_67](https://user-images.githubusercontent.com/56404567/216802670-236e935c-4887-4998-b80f-2e5fc1015666.png)

**Additional context**
I tried disabling every single firewall protection and windows defender feature that would interfere on the connection to the servers. I try puting admin rights on every executable of the launcher and game files and still doesnt work. Tried re-installing the game 4 times, deleting launcher and game old files and still no success

**Comment by QuentinGruber** [comment]
Thanks for your report, this issue happened to a lot of people, will work on this asap 🤠

**Comment by seishes** [comment]
thanks for the fast reply. Waiting anxiously hahahahhaah. I havent played this game since 2014-2015. The best survival game of all time. Really appreciate the hard work from you guys to bring this master piece back to life.

**Comment by QuentinGruber** [comment]
Hey @seishes still don't work ? I don't find anything about that sadly.

**Comment by QuentinGruber** [comment]
> After alot of attempts and reverse engineering I found the problem. If I wait the load screen all by it self, it locks the lobby commands. So I can’t join any server ou retrieve any information about it. I believe that the problem is with the timer set to the lobby requests or other things that are interfering with the lobby requests. To fix it, I simply open the game really fast and click the intro as fast as I can, jumping the cut scenes. This work flawlessly every single time.
> 
> FIX TO THE PROBLEM = OPENING THE GAME AND JOIN THE SERVER AS FAST AS YOU CAN
> 
> Observation : I had to ask a friend of mine to get my account key and create a profile on the server first so I can join

weird but it's true that i always skip the intro and join fast lmao

**Comment by seishes** [comment]
lol that’s why you didn’t even had a clue of what was going on. I attempted a lot of things (removing and editing alot of the server files) and this was the simplest workaround that fixed it . Anyway, thanks for the attention and again I really appreciate the effort from you guys bringing this game back to the survival scene again. I already had alot of Epic nostalgic moments playing this game again. So really, thanks alot guys
