### ISSUE TITLE
Error when starting launcher.

### ISSUE THREAD

**Issue by Timpa19** [QuentinGruber/h1z1-server#1347]
![61AE5A8B-5D74-4C8C-9169-69A7E22B807B](https://user-images.githubusercontent.com/124501348/216816636-5ecbb9f0-3ec3-4338-9171-cbe39e05d1ba.jpeg)
![9E7FBC98-1213-438C-9F49-012287D2FB41](https://user-images.githubusercontent.com/124501348/216816653-588a217b-d97b-4131-afe8-7c039c7dcf70.jpeg)
I have never had any problems with the game up until yesterday when an error stops me from using the launcher. Ive tried reinstalling the game and launcher way too many times and fixing with my files but i do now know how to solve this at all.

**Comment by Timpa19** [comment]
![Uploading BCA0ED34-5FBC-4858-9814-052C650D315D.jpeg…]()

**Comment by 0-x-2-2** [comment]
https://github.com/H1emu/h1emu-launcher

**Comment by Timpa19** [comment]
> 

can u be more specifik? do i need to download anything special in there? cuz ive downloaded the launcher a bunch oif time from github but nothing works.

**Comment by QuentinGruber** [comment]
Wrong repo see https://github.com/H1emu/h1emu-launcher/issues/25
