### ISSUE TITLE
DecayManager.decayDamage Unhandled rejection at  Promise

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1369]
Unhandled rejection at  Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading '0xdc61faaeeece4bb5')
      at DecayManager.decayDamage /opt/h1z1-server/out/servers/ZoneServer2016/managers/decaymanager.js:86:24)
      at /swizzle/H1emu-community-server-install/h1z1-server/out/servers/ZoneServer2016/managers/decaymanager.js:105:22
      at Array.forEach (<anonymous>)
      at DecayManager.contructionDecayDamage /opt/h1z1-server/out/servers/ZoneServer2016/managers/decaymanager.js:104:57)
      at DecayManager.run /opt/h1z1-server/out/servers/ZoneServer2016/managers/decaymanager.js:27:18)
      at DecayManager.run /opt/h1z1-server/out/servers/ZoneServer2016/managers/decaymanager.js:32:14)
      at runNextTicks (node:internal/process/task_queues:60:5)
      at process.processTimers (node:internal/timers:504:9)
} reason: TypeError: Cannot read properties of undefined (reading '0xdc61faaeeece4bb5') at Tue Feb 07 2023 15:43:04 GMT-0500 (Eastern Standard Time)
Process exited with code: 1 time : Tue Feb 07 2023 15:43:04 GMT-0500 (Eastern Standard Time)
h1z1-server V0.23.6-0 by H1emu community

**Comment by avcio9** [comment]
That error was pre 0.23.6, should not be a thinga anymore, lets see

**Comment by QuentinGruber** [comment]
> That error was pre 0.23.6, should not be a thing anymore, lets see

kk will do this https://github.com/QuentinGruber/h1z1-server/issues/1370 so we don't take reports for older versions
