### ISSUE TITLE
CHARACTER'S NAME

### ISSUE THREAD

**Issue by MMNILSAO** [QuentinGruber/h1z1-server#1384]
WELL, EVERY TIME I LOGO IN THE GAME, MY CHARACTER'S NAME CHANGES OR DISAPPEARS, A DIFFERENT NAME THAT I DIDN'T CREATE APPEARS, FROM THEN I LOSE ALL LOOT, I CAN NO LONGER ENTER MY BASE, AND I'M DIRECTED TO A REMOTE AREA OF THE MAP AS IF IT WAS THE FIRST TIME ON THE SERVER, I ALREADY REINSTALLED THE EMULATOR BUT IT PERSISTS, CAN YOU HELP ME?

**Comment by QuentinGruber** [comment]
Sorry we don't read caps
