### ISSUE TITLE
3 taps

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1395]
https://clips.twitch.tv/BenevolentCoyButterflyArgieB8-qDji0GrH8RI46k0k
https://clips.twitch.tv/BombasticRefinedSrirachaTF2John-wuY9X7WpsJq3ilil

**Comment by Z1Meme** [comment]
basically all weapon dmg values need to be redone, as well as helmet and kevlar damage reduction.

**Comment by Z1Meme** [comment]
@QuentinGruber @avcio9  Fixed?

**Comment by QuentinGruber** [comment]
> @QuentinGruber @avcio9 Fixed?

don't saw it anymore so probably yes
