### ISSUE TITLE
Vanish Bug

### ISSUE THREAD

**Issue by RywaZ** [QuentinGruber/h1z1-server#1401]
when i activate the /vanish and i activate the first person i am blocked i can't remove it anymore

Examples : https://streamable.com/whjdmm

**Comment by Zam6969** [comment]
Same issue :(

**Comment by BryanMacleod** [comment]
@Zam6969 try it and let me know

**Comment by QuentinGruber** [comment]
It's still an issue

**Comment by QuentinGruber** [comment]
well it's due to the fact that we enable spectator mode and it seems to lock to 1st person, if we find a way to still display nametag from huge distance ( wallhack ) then we could remove the use of the spec mode and fix this issue
