### ISSUE TITLE
Can't respawn after awaiting for zone lockout to disapear

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1403]
![image](https://user-images.githubusercontent.com/47059878/218340394-12bc3761-25d0-4e66-8448-776fc5391432.png)

**Comment by Z1Meme** [comment]
Need to resend the updatelockout packet once any zone reaches 0 @avcio9

**Comment by avcio9** [comment]
I cant replicate this, waiting 5 minutes and spawning just fine.
Maybe you got kicked for inactivity or something?
We could resend it while character is dead with each GetRespawnPositions packet received
