### ISSUE TITLE
Spectate Bug With Admins (cant spectate) 

### ISSUE THREAD

**Issue by Zam6969** [QuentinGruber/h1z1-server#1408]
You can produce this by going into spectate and the spectate camera acts like the player is stuck in one spot and wont render players past the distance you originally were before typing /spectate

Example https://wtfzammu.xyz/u/uwu/z5i1yp.mp4

**Comment by QuentinGruber** [comment]
duplicate of https://github.com/QuentinGruber/h1z1-server/issues/1286
