### ISSUE TITLE
Logout glitching

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1412]
Should detect when a player is autorunning and block them from logging out, and/or ignore position updates after the logout timer is finished.

**Comment by Z1Meme** [comment]
This would fix people being able to get under / through entire foundations by autorunning into them and logging out / back in after.

**Comment by Zam6969** [comment]
i kinda have bases loading faster on my server

**Comment by Zam6969** [comment]
server.sendConstructionData(client); before  ClientFinishedLoading kinda made it faster

**Comment by QuentinGruber** [comment]
The new loading time should fix that
