### ISSUE TITLE
Voice chat

### ISSUE THREAD

**Issue by 0-x-2-2** [QuentinGruber/h1z1-server#1439]
You can get Vivox to attempt to connect with this snippet on the server. 
```ts
      server.sendData(client, "Voice.Login", {
        clientName: '[issuer or Vivox admin username]', // fload02985-Fu36-dev-Admin
        sessionId: '[password or jwt]', // [vivox admin password works here]
        url: 'https://mt1s.www.vivox.com',
        characterName: '.[issuer].[username].' // fload02985-fu36-dev
      });
```

The issue is that this will call `vx_req_account_login_create` with the Vivox API but if voice still works on Z1 BR, slightly newer versions of the Vivox libraries are still ABI compatible and can be replaced then we just need packet decrypted dumps of `Voice.Login` and `Voice.JoinChannel` but the best option would most likely be hooking and redirecting the `vx_req_account_login_create` to the modern JWT login flow unless we can find documentation for the `vx_req_account_login_create` login flow but it is very hard to get it working as it seems to throw an internal error when using it with my account type.

I heard that some people got voice working on the 2015 build but I don't see code related to it anywhere.

Here are some tools useful for the JWT token generation flow:
https://github.com/LeafChage/vivox-token
https://cdn.discordapp.com/attachments/1069493856724320336/1071461084092964894/vivox_admin.py

**Comment by Z1Meme** [comment]
Already in-game using custom voice client/server.
