### ISSUE TITLE
Cannot punch

### ISSUE THREAD

**Issue by Dangotu** [QuentinGruber/h1z1-server#1445]
When I am playing the game no matter what server or region I am on I am unable to punch or swing melee weapons. I just started playing today so this may be known but I don't know how to farm anything to base build. Also I have no items showing in containers when I search them, once again this may be known but I want to verify I am not missing game files or something causing the issue. If someone could reach back out and let me know that would be great. I had almost 800 hours in Just Survive so I was excited when I found this. Thanks in advance, Dangotu

**Comment by Zam6969** [comment]
@Dangotu This is a Known bug thanks.

**Comment by Zam6969** [comment]
there is a current work around for the crowbars and the axe but that's it.

**Comment by Dangotu** [comment]
Awesome thanks for the Info, It was primarily for farming so that helps a ton!

**Comment by QuentinGruber** [comment]
Dupe of #985
