### ISSUE TITLE
Ban type "hiddenplayers" doesnt block networking of players but inverts it

### ISSUE THREAD

**Issue by buckclub** [QuentinGruber/h1z1-server#1477]
**Describe the bug**
When a player is banned with banType hiddenplayers, it doesn't block 100% of networking of players. It just networks players when they _shouldn't_ be networked. i.e. in a shack or shelter. 

**To Reproduce**
1. Ban a player with hiddenplayers
2. Spawn a player in a shack or shelter near him
3. You are able to hear / see him through cracks when you shouldn't

**Expected behavior**
Block networking of the player's information 100% of the time. This is the line that I believe causes this error.

`        const objectsToRemove = client.spawnedEntities.filter((e) => e && !(e instanceof Vehicle2016) && !(e instanceof ItemObject));
`

**Comment by Z1Meme** [comment]
has been disabled for a while
