### ISSUE TITLE
Explosion damages accross base walls

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1479]

**Comment by Z1Meme** [comment]
@QuentinGruber What does this mean?

**Comment by QuentinGruber** [comment]
> @QuentinGruber What does this mean?

Like being insta killed in a shack when someone is using ieds on your door is boring imo

**Comment by Z1Meme** [comment]
Todo: Explosives should check if a player / other damagable entities are inside a secured shelter before damaging

**Comment by QuentinGruber** [comment]
> Todo: Explosives should check if a player / other damagable entities are inside a secured shelter before damaging

**Comment by QuentinGruber** [comment]
Our explosion system isn't enought complex to handle that
