### ISSUE TITLE
No loot Display for any Cars/Cabins/Dressers etc. (Right Side)

### ISSUE THREAD

**Issue by Chronics2016** [QuentinGruber/h1z1-server#1501]
Hello,

i just installed the Game and didn´t change or modify anything. Play at Multiplayer on Main Server (test it on several Servers). The Game displays me no loot in any container i inspect (Cars/Dressers/Cabins/Lockers etc.). I Know it should apply on the right side but it dosen´t. All other features work fine. Loot in the world from tabels etc. i can collect normal. Try to reiinstall and Re-patch several times nothing change. Here is a Screenshot when i interact with a car nothing appers on the right or left.

![H1Z1 Bug](https://user-images.githubusercontent.com/127565491/224440775-ba9247b0-ecfc-4c72-a5e5-8fc2795e946d.PNG)

Please help. Would love to enjoy the game.

Thanks.

Regards

Chronics

**Comment by QuentinGruber** [comment]
> Hello,
> 
> i just installed the Game and didn´t change or modify anything. Play at Multiplayer on Main Server (test it on several Servers). The Game displays me no loot in any container i inspect (Cars/Dressers/Cabins/Lockers etc.). I Know it should apply on the right side but it dosen´t. All other features work fine. Loot in the world from tabels etc. i can collect normal. Try to reiinstall and Re-patch several times nothing change. Here is a Screenshot when i interact with a car nothing appers on the right or left.
> 
> ![H1Z1 Bug](https://user-images.githubusercontent.com/127565491/224440775-ba9247b0-ecfc-4c72-a5e5-8fc2795e946d.PNG)
> 
> Please help. Would love to enjoy the game.
> 
> Thanks.
> 
> Regards
> 
> Chronics

Hey thx for your report we will look at it! Also did you spawned naked like that ?

**Comment by Chronics2016** [comment]
no i spawn with t-shirt, waist and trousers but droppt them for the screenshot to make it more visible.

**Comment by Chronics2016** [comment]
I Don´t know if you do anything tonight but the Problem is solved =). Logged in now and it worked as it should be =) Love Ya

**Comment by QuentinGruber** [comment]
> I Don´t know if you do anything tonight but the Problem is solved =). Logged in now and it worked as it should be =) Love Ya

Well we've done nothing was an unknown client side issue then, have fun on the servers 🤠
