### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by Zam6969** [QuentinGruber/h1z1-server#1502]
Sometimes when loading into the server first time when launching the game you get a black screen and you just have to restart to fix it

**Comment by QuentinGruber** [comment]
> Sometimes when loading into the server first time when launching the game you get a black screen and you just have to restart to fix it

Not linked to server side, i believe it's something linked to razer or other UI stuff at game start

**Comment by 0-x-2-2** [comment]
This is a client renderer bug, you can reproduce this state by spawning the client outside of the world.
