### ISSUE TITLE
Menu music/Ingame Music Was working 

### ISSUE THREAD

**Issue by Zam6969** [QuentinGruber/h1z1-server#1519]
Menu music was working in old patches of h1emu login server like when  hax kit was introduced it got messed with now its not working at all also the tool tips and logo on the loading screen was working too now that's gone.. the login server packet was removed to initiate the music/tooltips/logo

**Comment by QuentinGruber** [comment]
> Menu music was working in old patches of h1emu login server like when hax kit was introduced it got messed with now its not working at all also the tool tips and logo on the loading screen was working too now that's gone.. the login server packet was removed to initiate the music/tooltips/logo

There is no serverside packets linked to that as far as i know, mostly an asset change

**Comment by Zam6969** [comment]
asset change meaning its client sided your saying? i had the same client and works on the old login serv and has music but when i load up the new one no music

**Comment by Zam6969** [comment]
@QuentinGruber

**Comment by QuentinGruber** [comment]
Just thought of it @Zam6969 i remember smth now, it's linked to what the zoneserver send at login not the loginserver, a change that we made broke that but it was a mandatory change that was more important than tooltips and music. Maybe a packet is sent too soon.

**Comment by Z1Meme** [comment]
> > Menu music was working in old patches of h1emu login server like when hax kit was introduced it got messed with now its not working at all also the tool tips and logo on the loading screen was working too now that's gone.. the login server packet was removed to initiate the music/tooltips/logo
> 
> There is no serverside packets linked to that as far as i know, mostly an asset change

This is due to the InitializationParameters packet being used now with Z1BR values, it's required for weapons and we didn't use it before. It's also the reason why blackberry bushes dont work without the workaround

**Comment by Z1Meme** [comment]
Need to reverse rulesets in InitializationParams for this.

**Comment by QuentinGruber** [comment]
> Need to reverse rulesets in InitializationParams for this.

**Comment by QuentinGruber** [comment]
Actually not i've just found that this come from the loginserver ( somehow )

**Comment by QuentinGruber** [comment]
> Actually not i've just found that this come from the loginserver ( somehow )

Ok the first loading song is handled by the loginserver ? and the actual musics in game by the zone server, the only thing i believe they share is character data so maybe a field in character data enable/disable this

**Comment by QuentinGruber** [comment]
It happened there : https://github.com/QuentinGruber/h1z1-server/compare/0.20.8...0.21.0
