### ISSUE TITLE
/unban crashes server

### ISSUE THREAD

**Issue by rxmario** [QuentinGruber/h1z1-server#1523]
Happened to us yesterday, but also heard it from other server owners that /unban crashes the server for some reason. I checked the logs but haven't found anything. Should be easy to reproduce tho I think

**Comment by QuentinGruber** [comment]
Thx! will look at it soon

**Comment by QuentinGruber** [comment]
> Happened to us yesterday, but also heard it from other server owners that /unban crashes the server for some reason. I checked the logs but haven't found anything. Should be easy to reproduce tho I think

Well can't reproduce that, don't you have an error log to provide ?

**Comment by rxmario** [comment]
> 

Unhandled rejection at  Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'loginSessionId')
      at ZoneServer2016.unbanClient (/home/ubuntu/moonshine/h1z1-server/out/servers/ZoneServer2016/zoneserver.js:3268:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.execute (/home/ubuntu/moonshine/h1z1-server/out/servers/ZoneServer2016/commands/commands.js:431:36)
} reason: TypeError: Cannot read properties of null (reading 'loginSessionId') at Tue Mar 21 2023 15:57:55 GMT+0000 (Coordinated Universal Time)
Process exited with code: 1 time : Tue Mar 21 2023 15:57:55 GMT+0000 (Coordinated Universal Time)

Think that must be it.

**Comment by QuentinGruber** [comment]
![image](https://user-images.githubusercontent.com/47059878/228619871-d1473cc2-674b-4c29-92db-fb4a25794c66.png)
I don't know how this could have happened, has it happened again? @rxmario

**Comment by rxmario** [comment]
Think Meme fixxed it 2 weeks ago here https://github.com/QuentinGruber/h1z1-server/commit/50bc0c11979aa89285832710b117abe360d7ca58 but it never got merged until this release :D Think we can close this with 0.26.2 @QuentinGruber

**Comment by QuentinGruber** [comment]
> Think Meme fixxed it 2 weeks ago here [50bc0c1](https://github.com/QuentinGruber/h1z1-server/commit/50bc0c11979aa89285832710b117abe360d7ca58) but it never got merged until this release :D Think we can close this with 0.26.2 @QuentinGruber
