### ISSUE TITLE
Server max pop cap let concurrent login 

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1538]

**Comment by Z1Meme** [comment]
@QuentinGruber what does this mean?

**Comment by QuentinGruber** [comment]
> @QuentinGruber what does this mean?

If current population of the server is 99/100 and two ppl join at the same time we can have 101 ppl in the server, basically the server pop isn't updated while a client is in the login process

**Comment by QuentinGruber** [comment]
it's such a low priority that I prefer to close the issue

**Comment by QuentinGruber** [comment]
this would be fixed with https://github.com/QuentinGruber/h1z1-server/issues/1538
