### ISSUE TITLE
I'm having trouble connecting to servers

### ISSUE THREAD

**Issue by IgorFelex** [QuentinGruber/h1z1-server#1593]
**Describe the bug**

I'm having trouble accessing some servers. I press click to start and nothing happens

**To Reproduce**
on the total server I can log in using vpn programs on others, I can't even use it

**Screenshots**

https://github.com/QuentinGruber/h1z1-server/assets/132942327/0e2540da-b0eb-4662-b62a-0e9e5c1f5afd

**Comment by QuentinGruber** [comment]
Hey @IgorFelex servers can reject you connection ( that's what happening there ) open a ticket on discord and precise which servers reject your connection thanks :cowboy_hat_face:

**Comment by QuentinGruber** [comment]
https://discord.com/invite/RM6jNkj
