### ISSUE TITLE
Shotgun

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1596]
> I think you guys should focus on fixing the shotgun, Its not working like it used to someone survive 6 pumps to the body and will still have their kev on , You can 1 tap someone in the headsometimes but its like 50/50, please focus on this for next wipe and it would be great! - Dex

**Comment by Z1Meme** [comment]
Kevlars need to absorb 90% of the damage based on the health of the armor before damaging the player.

**Comment by QuentinGruber** [comment]
> Kevlars need to absorb 90% of the damage based on the health of the armor before damaging the player.

Still relevant ?
