### ISSUE TITLE
Well it just says that I am not verified when trying to join the servers. 

### ISSUE THREAD

**Issue by Munkenn** [QuentinGruber/h1z1-server#1603]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Munkenn** [comment]
![image](https://github.com/QuentinGruber/h1z1-server/assets/136956973/e5773c78-4cad-49ff-b2d6-6fd10a8e78b0)

**Comment by Z1Meme** [comment]
This is not the correct place to post this. You need to follow the video in the #how-to-play channel of the discord to get verified.
