### ISSUE TITLE
/build command doesn't work anymore

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1608]
And it's kinda usefull when you try stuff with bases

**Comment by Z1Meme** [comment]
Can't recreate the issue. What branch / version did you try this on? Also please reply to me on discord DMs.

**Comment by Z1Meme** [comment]
@QuentinGruber

**Comment by QuentinGruber** [comment]
sorry mybad it's good @Z1Meme !
