### ISSUE TITLE
Game will not start

### ISSUE THREAD

**Issue by muffinhood** [QuentinGruber/h1z1-server#1613]
**Describe the bug**
After opening the launcher and starting the game . it stays in loading screen to the game for about 20 seconds and then closes the game on its own. was working totally fine yesterday. I have tried updating everything to no avail

**To Reproduce**
3. Scroll down to '....'**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by QuentinGruber** [comment]
Hey @muffinhood it was a temporary issue with the loginserver it's good now it's it ? :cowboy_hat_face:
