### ISSUE TITLE
Weapons?

### ISSUE THREAD

**Issue by muffinhood** [QuentinGruber/h1z1-server#1617]
**Describe the bug**
just curious if weapons will be fixed anytime? been down for a bit now

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by QuentinGruber** [comment]
What you mean by "fixed" ? @muffinhood do you talk about melee weapons ?

**Comment by muffinhood** [comment]
Guns. The animation is not working and also cannot be fired as well
