### ISSUE TITLE
requesting everyone to switch to wildlife server

### ISSUE THREAD

**Issue by muffinhood** [QuentinGruber/h1z1-server#1618]
Main Server US does not work for weapons . cannot have proper combat. Urging players and any new players to start on the "wildlife" server. it is fully functional , lets get  a server population going!!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QuentinGruber** [comment]
> Main Server US does not work for weapons . cannot have proper combat. Urging players and any new players to start on the "wildlife" server. it is fully functional , lets get a server population going!!
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

lmao where do you think you're , and main US server has been restarted to fix this issue. This kind of message belongs to discord not Github
