### ISSUE TITLE
Add an auto-reboot timer

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1619]

**Comment by Z1Meme** [comment]
Should do this asap since main servers need to be manually restarted after 140 hours or else all weapons stop working

**Comment by Z1Meme** [comment]
Basically just need to process.exit() the server after a configurable timer (set in yaml config), and have docker restart the process automatically.

**Comment by QuentinGruber** [comment]
i'm doing it rn
