### ISSUE TITLE
BUG SERVER Inhumanity and Main server (EU)

### ISSUE THREAD

**Issue by karnivar** [QuentinGruber/h1z1-server#1656]
I try to enter the inhumanity server and it won't let me, at the top left it appears in red godmode and neither my doll nor anything appears, after a while it disconnects me, the Main server is also buggy, the character bugs himself and takes off his clothes or change weapons and they don't disappear, and you can't attack other bases because of this bug, once you put it on the ground to destroy a door you can't recover it, turn it on or anything.

**Comment by QuentinGruber** [comment]
Not linked to this repo
