### ISSUE TITLE
VPN Whitelisting

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1699]
Should be able to whitelist certain authKeys to use VPNs.

**Comment by QuentinGruber** [comment]
So like a whitelist collection on mongo?

**Comment by Z1Meme** [comment]
Yep, should be just an authKey and a is whitelisted bool with maybe the name of the admin also

**Comment by QuentinGruber** [comment]
i choosed to use the zoneSessionId
