### ISSUE TITLE
Game crash causes player to not be able to login for ~30 seconds until the client is deleted serverside

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1701]
When a player incorrectly leaves the server (game crash, alt+f4, etc) they will crash again if trying to login within 30 seconds of the crash.

**Comment by QuentinGruber** [comment]
> When a player incorrectly leaves the server (game crash, alt+f4, etc) they will crash again if trying to login within 30 seconds of the crash.

Yep that's how work the timeout system, for me that would be a "won't fix".
How to "fix" that? Eject the old client still in server memory ? If so remember to execute the functions trigger at timed out logout

**Comment by Z1Meme** [comment]
> > When a player incorrectly leaves the server (game crash, alt+f4, etc) they will crash again if trying to login within 30 seconds of the crash.
> 
> Yep that's how work the timeout system, for me that would be a "won't fix".
> How to "fix" that? Eject the old client still in server memory ? If so remember to execute the functions trigger at timed out logout

I think if the client is logging in with the timeout still active, we activate the timeout early to allow the client to reconnect
