### ISSUE TITLE
Point and report player still works

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1719]
**Describe the bug**
Avcio originally made a commit to fix this (4e1242b345f0cd2767c986c65eb97ffae4b6d635), but it is still working to this day and commonly used to find other players.

**To Reproduce**
1. Find a player and press ctrl + r. You will hear a camera flash noise indicating there is a player. You won't hear anything if there isn't a player.

**Video**
https://github.com/QuentinGruber/h1z1-server/assets/49224688/4fd74a69-443e-43de-a01d-cd348c9439f1

**Comment by Z1Meme** [comment]
Not really planning on removing this at this time.
