### ISSUE TITLE
PvE need different Rules (PvP Problem)

### ISSUE THREAD

**Issue by DaEgo** [QuentinGruber/h1z1-server#1740]
Serval Items does Damage to Player, this must be changed.
I test no all so far.

1. Place a IED and Player walk/drive over it and it kills Player/Cars with Passengers.
2. Axe (and other Weapons like Guns) destroy West and Helmet.
3. Close Combat Weapons have a bleeding Effect, this kills Player.
4. Not tested Arrows (Gas Fire Explosive) cause i cant "load" it to a Bow but maybe also do damage to Player.

**Comment by QuentinGruber** [comment]
I was aware about number 2, found it funny enough to not patch it when i released PVE :sweat_smile: , thx !

**Comment by DaEgo** [comment]
yeah, could be point 99 on a list 😎
