### ISSUE TITLE
Base abandon - vanish Timer ?

### ISSUE THREAD

**Issue by DaEgo** [QuentinGruber/h1z1-server#1742]
There are a lot of abandoned bases, they just put a gate on it and never come back.

I noticed that you can't claim them.
A friend deleted his character and created a new one,
he cannot claim his old base either.

And what about automatic destruction?
Every day it should get a little less, most of them have a gate on them but it doesn't have a "life bar" and you can't see the progress.
Do you have an “internal” life bar that we don’t see?
If not, they'll sit around forever.

And how much is set?
Every day x?% less until automatic destruction?
And can you still claim beforehand?
How much time does it take to claim?
Is claiming actually active?

If it were up to me, all bases should be automatically deleted after, for example, 2 weeks of player inactivity.

Would be nice to know something about it.

**Comment by QuentinGruber** [comment]
Hey @DaEgo we do have a decay manager https://github.com/QuentinGruber/h1z1-server/blob/master/src/servers/ZoneServer2016/managers/decaymanager.ts if you wanna take a look :)
