### ISSUE TITLE
Missing Models (Rigged Light + Corn Mash)

### ISSUE THREAD

**Issue by DaEgo** [QuentinGruber/h1z1-server#1743]
Various objects that you can build/set up
don't have a model and that's why it doesn't work.
I added 2 that caught my eye.
(Also noticed it with serval Hospital Quest items)

![H1Z1 Corn Mash No Model](https://github.com/QuentinGruber/h1z1-server/assets/1351055/18d1d01f-c861-4ce5-80ed-2d11bf69bf94)

![H1Z1 Rigged Light No Model](https://github.com/QuentinGruber/h1z1-server/assets/1351055/7e69c25f-39c6-455d-a1c7-308569cea09c)

**Comment by QuentinGruber** [comment]
it doesn't miss only there models but also their logic like for hospital quest items.

**Comment by DaEgo** [comment]
placement Rigged Light works
but there is no light
