### ISSUE TITLE
PvE ! Airdrop not possible cause not enough Player online

### ISSUE THREAD

**Issue by DaEgo** [QuentinGruber/h1z1-server#1745]
I play on PvE and notice that there are not so much Player on.
Called Airdrop "always" say : Not enough Player online.
Can you please edit the needed amount of online player ?
On PvE maybe with 3 or 5 Player at the evening could work maybe.

**Comment by QuentinGruber** [comment]
Min survivors for airdrop has been changed to 1 on HELP pve server :)
