### ISSUE TITLE
Hand Shovel = No Permissions ?!

### ISSUE THREAD

**Issue by DaEgo** [QuentinGruber/h1z1-server#1753]
Hand Shovel create a Model but its useless
Cant open it
Cant destroy it with Demo Hammer

![Hand Shovel](https://github.com/QuentinGruber/h1z1-server/assets/1351055/7b5bdc34-0374-457b-ab57-d03c5bf74681)

**Comment by QuentinGruber** [comment]
Thx for the report @DaEgo , will look at that when i'm done on #1721 :cowboy_hat_face:  ( but if others want to, they can )
