### ISSUE TITLE
Ban propagation doesn't work anymore

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1802]
Ban-light seems to be inactive

**Comment by Piranha12** [comment]
I banned my alternate account on Main EU using the command /banid and /ban. I wasn't able to rejoin Main EU or US, but I was able to join Community servers and play.

**Comment by QuentinGruber** [comment]
> I banned my alternate account on Main EU using the command /banid and /ban. I wasn't able to rejoin Main EU or US, but I was able to join Community servers and play. Also, banning my alt account also made it so I can't log into my main account.

Yes due to your ip being the same and being banned, i will look at why it doesn't work properly

**Comment by QuentinGruber** [comment]
Maybe this is due to custom code being used only on the live-login-server which is not public
