### ISSUE TITLE
Way too low spawn rate of fert @bumjick and other loot respawn issues

### ISSUE THREAD

**Issue by SONNY-1812** [QuentinGruber/h1z1-server#1826]
Hey guys I just wanted to get in touch because I have a request that has been on my mind for a long time.
I've been actively playing on the main server for about 10 wipes now and it's so frustrating that there is no fertilizer on the bumjick farm. Sometimes you can't even get 4 fert together per round.
And yes, I also use the north route, but there are hardly any fertilizers there either.
It's always really bad when there are few players on the server.
I've also noticed that when there are few players online, hardly any loot spawns or takes ages to respawn.
Couldn't you make sure that the loot respawn timer is changed and that more fertilizer spawns at the bumjick farm?
<@149313739986960384>

**Comment by SONNY-1812** [comment]
note: its getting extremely bad when player count drops below 20 players...

**Comment by SONNY-1812** [comment]
back then when fertilizer was avadible in all storage halls around the map: https://www.youtube.com/watch?v=gCDJL4-oxnw

**Comment by SONNY-1812** [comment]
back then when fert was avadible in dumpsters and in the back of gas stations (small boxes) everywhere around the map: https://www.youtube.com/watch?v=RR-gce6C-ik

**Comment by SONNY-1812** [comment]
btw fert was avadible everywhere in small medium and large boxes

**Comment by QuentinGruber** [comment]
> back then when fert was avadible in dumpsters and in the back of gas stations (small boxes) everywhere around the map: https://www.youtube.com/watch?v=RR-gce6C-ik

They do spawn in there currently
