### ISSUE TITLE
Players being able to walk on other bases gates

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1843]
**Describe the bug**
Currently players can walk on other bases gates and even sit there and door camp a fully walled off base... which is incredibly boring in my opinion. I've had this happen multiple times and should be looked into.

**To Reproduce**
Boost on top of a car to get onto someones gates (or just get on top with a car and jump down) and observe

**Expected behavior**
Should detect the player is inside the CubeBounds range and teleport them out, not letting them afk or run on top.

**Screenshots**
https://streamable.com/ldhl7h

**Comment by jasonmoonen** [comment]
I strongly advise against this, in the original game you were able to do this. Also, this makes the combat way more engaging if you're able to infiltrate bases.
