### ISSUE TITLE
99% of cabinet or storage loot is canned food

### ISSUE THREAD

**Issue by SONNY-1812** [QuentinGruber/h1z1-server#1870]
Hey guys

I think something went wrong when you added " Added all canned food types & removed coded messages from Kitchen Cabinets".
99% of the time canned food is spawning in all cabinets and storages (campsites).
Thats really annoying.
Before it was bullets, lighters, locker keys, sugar, vehicle keys....
I will add some screenshots.

![20240127233042_1](https://github.com/QuentinGruber/h1z1-server/assets/123518218/cb4bfcb7-e839-431d-b4b7-28d24f26ac71)
![20240129000919_1](https://github.com/QuentinGruber/h1z1-server/assets/123518218/d797feb1-3e2c-4a53-afd7-09db1fd61c65)
![20240129001502_1](https://github.com/QuentinGruber/h1z1-server/assets/123518218/b80cfe8d-6ad9-48df-9ca4-eaee48d5732d)
![20240129001516_1](https://github.com/QuentinGruber/h1z1-server/assets/123518218/5516fafb-ce95-48d5-af66-f0d144327dca)

**Comment by QuentinGruber** [comment]
Linked to #1852

**Comment by QuentinGruber** [comment]
> Hey guys
> 
> I think something went wrong when you added " Added all canned food types & removed coded messages from Kitchen Cabinets". 99% of the time canned food is spawning in all cabinets and storages (campsites). Thats really annoying. Before it was bullets, lighters, locker keys, sugar, vehicle keys.... I will add some screenshots.
> 
> ![20240127233042_1](https://private-user-images.githubusercontent.com/123518218/300301127-cb4bfcb7-e839-431d-b4b7-28d24f26ac71.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTE4MTgsIm5iZiI6MTcwNjcxMTUxOCwicGF0aCI6Ii8xMjM1MTgyMTgvMzAwMzAxMTI3LWNiNGJmY2I3LWU4MzktNDMxZC1iNGI3LTI4ZDI0ZjI2YWM3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDc4ZTg5OTMyYmRkYmFmMWQ1OTE2MGZhODhmMDliMGE0MTRkMDUwNTVjMTNhYzNiMWNlMWYxOWNlNjYxNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P7k3d0FK6G_pRch-Lrmqn9K49Cco9YFBbn_e0xb4y30) ![20240129000919_1](https://private-user-images.githubusercontent.com/123518218/300301130-d797feb1-3e2c-4a53-afd7-09db1fd61c65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTE4MTgsIm5iZiI6MTcwNjcxMTUxOCwicGF0aCI6Ii8xMjM1MTgyMTgvMzAwMzAxMTMwLWQ3OTdmZWIxLTNlMmMtNGE1My1hZmQ3LTA5ZGIxZmQ2MWM2NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzVhYjAyZDMwYWVlN2MzYmVjZTcyOGJkMzgzY2NmOTY0MDEzNGI5OWU3NTU5ZGM3MmVmMWYwNDk0ZmRhNzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B-cgP0PJf6iSR8loK38WYbxS4_cOZ6lEtL7I5eTTwG0) ![20240129001502_1](https://private-user-images.githubusercontent.com/123518218/300301038-b80cfe8d-6ad9-48df-9ca4-eaee48d5732d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTE4MTgsIm5iZiI6MTcwNjcxMTUxOCwicGF0aCI6Ii8xMjM1MTgyMTgvMzAwMzAxMDM4LWI4MGNmZThkLTZhZDktNDhkZi05Y2E0LWVhZWU0OGQ1NzMyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTYzOWYyZjBkNGNlNzA5MDM4OGViMGFlMDFhNjI2MjEwMzI4OTA4OThlNTFhYWZlYjBkMWMyYWU2OTJmOWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6F29pANz-X_IPI1jhKwzdS81Q3nt1odJEPESyEu-W1Q) ![20240129001516_1](https://private-user-images.githubusercontent.com/123518218/300301039-5516fafb-ce95-48d5-af66-f0d144327dca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTE4MTgsIm5iZiI6MTcwNjcxMTUxOCwicGF0aCI6Ii8xMjM1MTgyMTgvMzAwMzAxMDM5LTU1MTZmYWZiLWNlOTUtNDhkNS1hZjY2LWYwZDE0NDMyN2RjYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNDMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQ2MTEyNzViYmEyYjc0MTg1MTZiYzY0ODFiNDVjYWE1ZTdjYjNiNWQ2MzI1YTc5NmYwODVkMmE2ODcyZmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a_4FGYf791kbABInv9mlFfS_iBgXXoWgmsfv-J21VWY)

Before it was only salt lighter and vehicle keys , they're still in the lootable but since there is too much canned food variant they spawn rarely, gonna change that.
