### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1884]
**Describe the bug**
A good amount of players have recently reported that they're getting infinite loading screens, and restarts don't fix the issue.

**To Reproduce**
Not known currently

**Comment by QuentinGruber** [comment]
Directly at login or at zone load ? @Nikolassparrow

**Comment by Nikolassparrow** [comment]
> Directly at login or at zone load ? @Nikolassparrow

During when the player loads in the server. It doesn't happen to all servers, just specific ones where the bug occurs.

**Comment by QuentinGruber** [comment]
`[ERROR] Mongo character not found! characterId:` sometimes in logs we do have this error this could be linked

**Comment by QuentinGruber** [comment]
any news on this ? @Nikolassparrow

**Comment by Nikolassparrow** [comment]
> any news on this ? @Nikolassparrow

Nope, users are still reporting this though.

**Comment by QuentinGruber** [comment]
https://github.com/QuentinGruber/h1z1-server/pull/1958
