### ISSUE TITLE
Modify the loot spawn to make it more survival-like

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1929]
- revert https://github.com/QuentinGruber/h1z1-server/pull/1907 or at least adapt spawn chances

- revert spawn chances for world items 

- Remove skinning knife from startup inventory

**Comment by Nikolassparrow** [comment]
> * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> * revert spawn chances for world items
> * Remove skinning knife from startup inventory

I've been working on loot spawns and was going to open a branch sometime this week for it. 

Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016.
https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.

**Comment by Nikolassparrow** [comment]
Also why do you want to revert #1907? This was a bug with loot containers and reverting it will cause it to be broken again. The rates need to be adjusted which is what I was working on with the loot spawn update that I dm'd kentin about.

**Comment by QuentinGruber** [comment]
> > * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> > * revert spawn chances for world items
> > * Remove skinning knife from startup inventory
> 
> I've been working on loot spawns and was going to open a branch sometime this week for it.
> 
> Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016. https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.

Or at least that the skinning knife can break, so we have a reasons to craft a new one

**Comment by QuentinGruber** [comment]
> Also why do you want to revert #1907? This was a bug with loot containers and reverting it will cause it to be broken again. The rates need to be adjusted which is what I was working on with the loot spawn update that I dm'd kentin about.

it was more of a reminder that anything, adjusting the rates is the right move

**Comment by Nikolassparrow** [comment]
> > > * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> > > * revert spawn chances for world items
> > > * Remove skinning knife from startup inventory
> > 
> > 
> > I've been working on loot spawns and was going to open a branch sometime this week for it.
> > Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016. https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.
> 
> Or at least that the skinning knife can break, so we have a reasons to craft a new one

I agree, would be a nice change 👍 :D I will look into that! Maybe add something like 5 damage to the harvesting knife per hit? How much HP though?

**Comment by Nikolassparrow** [comment]
> > Also why do you want to revert #1907? This was a bug with loot containers and reverting it will cause it to be broken again. The rates need to be adjusted which is what I was working on with the loot spawn update that I dm'd kentin about.
> 
> it was more of a reminder that anything, adjusting the rates is the right move

#1930 :D

**Comment by QuentinGruber** [comment]
> > > > * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> > > > * revert spawn chances for world items
> > > > * Remove skinning knife from startup inventory
> > > 
> > > 
> > > I've been working on loot spawns and was going to open a branch sometime this week for it.
> > > Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016. https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.
> > 
> > 
> > Or at least that the skinning knife can break, so we have a reasons to craft a new one
> 
> I agree, would be a nice change 👍 :D I will look into that! Maybe add something like 5% damage to the harvesting knife per hit? How much HP though?

Or just a random chance that it broke during the process ?

**Comment by Nikolassparrow** [comment]
> > > > > * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> > > > > * revert spawn chances for world items
> > > > > * Remove skinning knife from startup inventory
> > > > 
> > > > 
> > > > I've been working on loot spawns and was going to open a branch sometime this week for it.
> > > > Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016. https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.
> > > 
> > > 
> > > Or at least that the skinning knife can break, so we have a reasons to craft a new one
> > 
> > 
> > I agree, would be a nice change 👍 :D I will look into that! Maybe add something like 5% damage to the harvesting knife per hit? How much HP though?
> 
> Or just a random chance that it broke during the process ?

Sure! What percent would you think would be good?

**Comment by QuentinGruber** [comment]
> > > > > > * revert [Fix containers not receiving entirety of loottable upon respawn #1907](https://github.com/QuentinGruber/h1z1-server/pull/1907) or at least adapt spawn chances
> > > > > > * revert spawn chances for world items
> > > > > > * Remove skinning knife from startup inventory
> > > > > 
> > > > > 
> > > > > I've been working on loot spawns and was going to open a branch sometime this week for it.
> > > > > Why do you want the skinning knife removed from the startup inventory? It spawned with players in December 2016. https://www.youtube.com/watch?v=aFpSNGow3QI (5:51) He clearly shows that he spawned with the skinning knife already in his inventory.
> > > > 
> > > > 
> > > > Or at least that the skinning knife can break, so we have a reasons to craft a new one
> > > 
> > > 
> > > I agree, would be a nice change 👍 :D I will look into that! Maybe add something like 5% damage to the harvesting knife per hit? How much HP though?
> > 
> > 
> > Or just a random chance that it broke during the process ?
> 
> Sure! What percent would you think would be good?

Idk 1/15 ? or 1/20 , so it could happen at least one time during the life of a character
