### ISSUE TITLE
Freeplaced Entities don't save on server restart

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1954]
1k reported this in the Discord.

**Describe the bug**
Freely placed entities don't save upon server restarts. This affects items like Hand Shovels/stashes, containers, furnaces, etc. 

**To Reproduce**
1. Place an entity freely around the world
2. Restart the server and observe the entity no longer being there.

**Expected behavior**
Freely placed entities and their containers should be saved upon server restarts like how entities placed in shelters/shacks do.

**Screenshots**
When I get some time today, I'll make a recording of this happening.

**Additional Context**:
This issue is highly likely to be unrelated, but does this maybe tie into #1467 ?

**Comment by QuentinGruber** [comment]
> 1k reported this in the Discord.
> 
> **Describe the bug** Freely placed entities don't save upon server restarts. This affects items like Hand Shovels/stashes, containers, furnaces, etc.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Place an entity freely around the world
> 2. Restart the server and observe the entity no longer being there.
> 
> **Expected behavior** Freely placed entities and their containers should be saved upon server restarts like how entities placed in shelters/shacks do.
> 
> **Screenshots** When I get some time today, I'll make a recording of this happening.
> 
> **Additional Context**: This issue is highly likely to be unrelated, but does this maybe tie into #1467 ?

not linked to #1467 we probably just not save them

**Comment by QuentinGruber** [comment]
i believe some freeplace we're removed but it's definitely and issue for stashes

**Comment by QuentinGruber** [comment]
@Nikolassparrow test removing this line https://github.com/QuentinGruber/h1z1-server/blob/master/src/servers/ZoneServer2016/zoneserver.ts#L1588

**Comment by QuentinGruber** [comment]
i don't remember why @jasonmoonen if he can help us on this

**Comment by jasonmoonen** [comment]
> i don't remember why @jasonmoonen if he can help us on this

Oh yeah that's an easy fix. The thing we should think about is decay for those entities. My suggestion would be to despawn those entities after 12 hours if not repaired. Suggestions are welcome of course.. Except for the hand shovels of course

**Comment by jasonmoonen** [comment]
Fix is on if you want to try [b49ca98078540c581c6556f6998447de867d03ad](https://github.com/QuentinGruber/h1z1-server/commit/b49ca98078540c581c6556f6998447de867d03ad)

**Comment by jefix88** [comment]
StorageContainers in Basic Shack also disappear after server restart, I don't know if anyone reported this.

**Comment by Nikolassparrow** [comment]
> Fix is on if you want to try [b49ca98078540c581c6556f6998447de867d03ad](https://github.com/QuentinGruber/h1z1-server/commit/b49ca98078540c581c6556f6998447de867d03ad)

https://streamable.com/4z0n45 Change looks good thanks man! 

@QuentinGruber just need to merge jasons bugfix/freeplace branch and this issue will be fixed :D

**Comment by Nikolassparrow** [comment]
> StorageContainers in Basic Shack also disappear after server restart, I don't know if anyone reported this.

Currently small shacks are disabled on the main servers due to a bug where it crashes client (I'm not sure if the cause has been found but disabling them is a reliable fix..)

**Comment by jefix88** [comment]
> > StorageContainers in Basic Shack also disappear after server restart, I don't know if anyone reported this.
> 
> Currently small shacks are disabled on the main servers due to a bug where it crashes client (I'm not sure if the cause has been found but disabling them is a reliable fix..) Should still be looked into for when they are re-enabled though.

BASIC SHACK is the smallest one, where you put everything on the ground. Furnace disappears too :D

**Comment by QuentinGruber** [comment]
> > > StorageContainers in Basic Shack also disappear after server restart, I don't know if anyone reported this.
> > 
> > 
> > Currently small shacks are disabled on the main servers due to a bug where it crashes client (I'm not sure if the cause has been found but disabling them is a reliable fix..) Should still be looked into for when they are re-enabled though.
> 
> BASIC SHACK is the smallest one, where you put everything on the ground. Furnace disappears too :D

nice to know @jefix88 , hopefully it's fixed, if not recreate an issue or comment this one :)
