### ISSUE TITLE
Freeplace entities inside shelters/shacks don't despawn for outside players

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#2000]
**Describe the bug**
In #1900, Meme mentions workbenches "despawn" inside shelters as a form of ESP protection. Currently this is not the case and ONLY works for players. This is something that people have commonly mentioned is an extremely frustrating feature to have in the game and some claim that "half of H1EMU has ESP." You currently are able to see storage boxes, furnaces, workbenches, essentially any free-placed entity inside of a shelter you can see.   

**To Reproduce**
1. Can use a shelter or shack to re-produce, will use a large shelter for demonstration purposes: 
2. Place a foundation with a large shelter and also place a door on it (any type works)
3. Place some boxes and workbenches maybe a couple furnaces too inside of the large shelter
4. Stand by one of the cracks in the large shelter and observe all of the players free-placed entities

**Expected behavior**
When a shelter or shacks door is closed, all entities inside should be "despawned" to outside players and remained spawned in for the players inside. When a door is open, all entities should be spawned into the world for outside players.

**Screenshots**
![a69d57c9ce290f382ecb4af6d90bfd8c](https://github.com/QuentinGruber/h1z1-server/assets/49224688/d1b516fd-6c28-4639-aaa5-069905b5151f)

**Additional context**
This one change can bring a MASSIVE QOL to H1EMU. Like I mentioned above, many players have commented that it feels as though there is an abundance of ESPers, but in reality I believe it's just people abusing this bug.

**Comment by QuentinGruber** [comment]
dup
