### ISSUE TITLE
Screen freezes for admins when running speed is set past the normal speed

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#2040]
**Describe the bug**
Essentially when you do /run, any value that is over 4 (the normal player speed), the players screen will freeze for a few seconds. I'm assuming this is an anti-hack feature but I believe it should be bypassed for admins/people in debug mode.

**To Reproduce**
1. Go on any server that you have admin on.
2. Do /run and set the value to anything higher than 4 (I usually do /run 25)
3. Run around and observe your screen freezing

**Expected behavior**
Allow the admin player to freely move around no matter the value of /run

**Screenshots**
https://streamable.com/y2bieg (clipped ended pre-maturely but you can still witness the bug)

**Additional context**
I noticed that there was a packet being sent when this happens called "Security" with an ID field to follow up with it. Like I mentioned above, I'm fairly certain this is some sort of anti-hack feature which would make sense why a Security packet is sent when this happens.

**Comment by QuentinGruber** [comment]
It would probably need client modifications since original admins had an admin client that probably didn't had these anti-hack features
