### ISSUE TITLE
0.35.1 Airdrop without aircraft or sound, the descent process model of the airdrop is a pickup truck

### ISSUE THREAD

**Issue by alvazhang79** [QuentinGruber/h1z1-server#2051]
**Describe the bug**
A clear andWhen I called for an airdrop using the airdrop code, I didn't hear the roar of the plane or see the plane. I only saw a pickup truck descending from the sky, but the materials in the airdrop box after landing were normal. concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**
See attachment
![D8EDF62B836EEB0774FB650683800844](https://github.com/QuentinGruber/h1z1-server/assets/45260445/fbf2df10-ac3f-4827-aa4a-ffb73612eb43)

**Additional context**

**Comment by QuentinGruber** [comment]
Ok tested it and yep the bug report is accurate, my guess is that some enums ids have been swapped :/ Gonna fix that :cowboy_hat_face:

**Comment by QuentinGruber** [comment]
Actually it's bc i made change to how vehicle creation works, so we use the vehicleId and not the actorId that's what created the issue there at least for the cargo being a pickup... and the plane being a jeep
