### ISSUE TITLE
cheater xyz G14 bug

### ISSUE THREAD

**Issue by zxywandxb111** [QuentinGruber/h1z1-server#2117]
If the player disconnects from the server as soon as he or she gets off the bus, then the player will have a certain probability of losing his or her character coordinates. In mongodb, XYZ will lose a character position, and the player will not be able to access the game, load the game indefinitely and after a while prompt for a G14 error. If ADMIN tphere is the player during loading, or if MONGODB forces a change to his left, then the player will log in

**Comment by zxywandxb111** [comment]
Get out of Vehicles

**Comment by zxywandxb111** [comment]
The Bug1. ATV driver, shot while driving, has a certain chance of still controlling the vehicle (trigger condition unknown)2. If the player is alone, if he drops the line, the car will refresh somewhere else. If there are other players around, it won't. 3. There is a certain probability that the vehicle on the foundation will disappear, in fact it will still be there, press E on the air to get in, and the model will recover 4.5% . On-line, if the vehicle first refreshes, after the foundation refreshes, the vehicle will fall under the foundation 5.5% . When the player gets in the car, there is a certain probability that the player's model will remain in place, and when the player gets out of the car, the model will be refreshed to the new position 6.5% . In the middle of the pickup truck, back to where he got in when he got out

**Comment by QuentinGruber** [comment]
> If the player disconnects from the server as soon as he or she gets off the bus, then the player will have a certain probability of losing his or her character coordinates. In mongodb, XYZ will lose a character position, and the player will not be able to access the game, load the game indefinitely and after a while prompt for a G14 error. If ADMIN tphere is the player during loading, or if MONGODB forces a change to his left, then the player will log in

when you say it "loose" it it populate it with 0 ? @zxywandxb111

**Comment by QuentinGruber** [comment]
bc for me it doesn't crash the game i just spawn at 0 0 0 0

**Comment by QuentinGruber** [comment]
i've created another issue for vehicles specific issues, now this issue will only serve the G14 bug so if you can give me steps to reproduce it, i could fix that ( i coulnd't reproduce the vehicle thing )

**Comment by QuentinGruber** [comment]
ok i got it by litterraly putting an empty array it produce the infinite load issue
