### ISSUE TITLE
I cant introduce my self on discord

### ISSUE THREAD

**Issue by VitorSibin** [QuentinGruber/h1z1-server#2140]
**Describe the bug**

**To Reproduce**
1. Go to discord for de first time
2. Click on introduce yourself

**Expected behavior**
I cant introduce my self

**Screenshots**
![image](https://github.com/user-attachments/assets/a4a89a1f-6f61-4c12-b8b3-2936000ec970)

**Additional context**

**Comment by JayyWayz** [comment]
This is not a bug you need to verify your Discord account through Double Counter.

**Comment by JayyWayz** [comment]
Follow this link to go to the verification channel https://discord.com/channels/707525351357677610/1213357941307215882
There should be a button you can press to verify

![image](https://github.com/user-attachments/assets/962ca371-87be-49f2-a6c2-3c1fe15978ba)

**Comment by QuentinGruber** [comment]
thx @JayyWayz

**Comment by VitorSibin** [comment]
Sorry to come back here, but the verification bot is not sending the link for validation, can anyone help me?

![image](https://github.com/user-attachments/assets/c431673c-570f-4dcc-ad2d-89f75fb503e2)

**Comment by JayyWayz** [comment]
@VitorSibin Your Discord may have been blocking the DM for some reason.

You have been manually verified
![image](https://github.com/user-attachments/assets/6a0aa5a5-79b9-472f-85a1-bacf3200758b)

Make sure to read read the [how-to-play](https://discord.com/channels/707525351357677610/861981974960013362/1277707333346263133) channel to gain access to the rest of the Discord and Authenticate your key.
