### ISSUE TITLE
Routine took too much time

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#2156]
Routine took 89ms to execute, which is more than the tickRate 75

**Comment by QuentinGruber** [comment]
i want to look back at this system

**Comment by resinate** [comment]
im curious where is Routine system ur talking about is at? what does it supposed to do?

**Comment by QuentinGruber** [comment]
> im curious where is Routine system ur talking about is at? what does it supposed to do?

client routine, sometimes it spike and i can't really reproduce it rn, but it seems it doesn't happen anymore on the current live server i have to check

**Comment by resinate** [comment]
actually thats funny i have the same issue right now as well, i get it ALOT when u use swizzle too

**Comment by QuentinGruber** [comment]
no idea
