### ISSUE TITLE
admin bug 

### ISSUE THREAD

**Issue by zxywandxb111** [QuentinGruber/h1z1-server#2174]
When an administrator uses/deepcover to change his r name to kill  player, the kill prompt and/Combatlog display the administrator's real name

**Comment by QuentinGruber** [comment]
in combat log that happens if the admin have given damage to the player before changing is name, and in the kill prompt it's because we use a game packet and somehow the name change is not replicated there

**Comment by QuentinGruber** [comment]
in the kill prompt the real admin name is only displayed to the admin itself
