### ISSUE TITLE
weapons stop working after server is up 120+ hours (FIXED)

### ISSUE THREAD

**Issue by resinate** [QuentinGruber/h1z1-server#2176]
has this long time bug still exist for v38+
when server is up for too long weapons and projectiles stop working. but everything else still works perfectly
melee, building, looting, killing zombies, farming all work. just not guns/projectiles

**Comment by resinate** [comment]
i am currently running a test on possible fix, but im only at 70 hours atm so itll be few days

**Comment by QuentinGruber** [comment]
something we can take in account in 120hours there is 432 000 000ms and the max uint32 is 4 294 967 295, i mean it's possible that somewhere we end up having a loo large number that make these packets being ignored by the game, so we have to look at the packets and test them

**Comment by resinate** [comment]
i made a code to refresh all definitions every hour, thats only thing i see mainly when server starts. basically im like soft rebooting server while server is live

**Comment by resinate** [comment]
i found this code, dont know if u guys updated and renamed everything but yea
thats why im testing reload definitions
![image](https://github.com/user-attachments/assets/a094188a-a6c9-4c4d-a37b-1232ce2a79c2)

**Comment by resinate** [comment]
my discord - 767761048156766209

**Comment by resinate** [comment]
i just noticed that not ONLY does weapons not send, but im still in godmode even tho i run around and jump and stuff
![image](https://github.com/user-attachments/assets/26d20581-a201-43c2-8349-352dec76635d)

**Comment by resinate** [comment]
i built hookmanager recycler to see if that fixes the issue

**Comment by resinate** [comment]
ok back with more updates
hook manager is not it
but i noticed this
ClientFinishedLoading(server, client, packet) {
runs twice when loading into the world. if its ran a 2nd time there has to be a reason for it

**Comment by resinate** [comment]
found the issue
server.hookManager.checkHook("OnClientFinishedLoading", client)

hookmanage, i disabled this and forced pack definitions on login.
![image](https://github.com/user-attachments/assets/4bfd670b-a1a1-48f9-9c43-28db65639772)
i would like to talk and show someone on discord about this.
unless u guys prefer not to fix this bug?

**Comment by Z2Doggo** [comment]
Resinated, it would be much preferred to show your changes and 'fixes' here on GitHub rather than showing one dev in a vc. Like your math teach in elementary once said? "Show your work and how you solved it."

**Comment by resinate** [comment]
i cant explain what i did, all i did was disable hook manager checks, thats all

**Comment by resinate** [comment]
i also built this code,

`    async updateWeaponStance(server, client) {
        server.sendAlert(client, "Procressing Definitions....");
        await server.sendRawData(client, server.itemDefinitionsCache);
        await server.sendRawData(client, server.weaponDefinitionsCache);
        await server.sendRawData(client, server.projectileDefinitionsCache);
        await server.sendRawData(client, server.profileDefinitionsCache);
        await utils_1.Scheduler.wait(250);
        server.sendData(client, "Character.WeaponStance", {
            // activates weaponstance key
            characterId: client.character.characterId,
            stance: 1,
        });
        server.sendData(client, "Synchronization", {
            serverTime: (0, utils_1.Int64String)(server.getGameTime()),
            serverTime2: (0, utils_1.Int64String)(server.getGameTime()),
        });
        client.character.updateEquipment(server); // needed or third person character will be invisible
        client.character.updateContainers(server, client);
        client.character.updateLoadout(server); // needed or all loadout context menu entries aren't shown
        let loadoutItem = client.character.getEquippedWeapon();
        if (server.isWeapon(loadoutItem.itemDefinitionId)) {
            server.switchLoadoutSlot(client, loadoutItem);
        }
        await utils_1.Scheduler.wait(500);
        server.setGodMode(client, false);
        server.sendAlert(client, "Procressing Definitions.... (Completed)");
    }`

**Comment by Z2Doggo** [comment]
Since you said you're still on version 24 of the server core, I'm question what you said at the end of your reply... "I gain nothing sharing this." Because neither do we, we're on version 39 at this point and this is pointless for such a big version difference.
