### ISSUE TITLE
split items from global entities

### ISSUE THREAD

**Issue by resinate** [QuentinGruber/h1z1-server#2187]
items in world should be split for better speeds from all objects. no point calling ALL items in world for certain checks not related to items.

**Comment by QuentinGruber** [comment]
yeah you're talking about the grid sys i guess

**Comment by resinate** [comment]
in my own src and in v30s, i noticed ALL entities in world were grouped into 1 very large pool. my suggestion which ive started it on my src, was spltting up major groups like
Items
objs
npcs

cuz i found it was faster to procress them in groups vrs constantly calling certain things when not needed. trying to explain this best i can. like picking up an item then removing it from render, scans ALL entities if this makes any sense.

**Comment by resinate** [comment]
something else i noticed, is when u delete an entity it scans WHOLE array on every execution of the code, when u say u run into pleasent city, ur mass un-rendering 100s of objects when running out of dist. ur scanning same array 100s of times, with 1000s of objects. might be way to optimize this.

**Comment by QuentinGruber** [comment]
but just asking why are you still on like v30 and talking about stuff on 10 versions prior ? Like how do you know it's not already fixed ?

**Comment by resinate** [comment]
ive been dling all recent versions and comparing code. and using Ai to optimize it or in some cases fully recode it.

**Comment by QuentinGruber** [comment]
> ive been dling all recent versions and comparing code. and using Ai to optimize it or in some cases fully recode it. right now im pretty much upto date on alot of fixes from u guys other than AI zombies. i have full server running. and been playing on it. one huge difference we have, ur guys server only handles like 50k objects im pushing 250k-300k objects. but ive been coding everything thru JS, some functions i dont know if they work in TS
> 
> ![image](https://private-user-images.githubusercontent.com/185112/380375817-1afba810-58a2-45c2-9606-b233986f6087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDQxNDksIm5iZiI6MTcyOTk0Mzg0OSwicGF0aCI6Ii8xODUxMTIvMzgwMzc1ODE3LTFhZmJhODEwLTU4YTItNDVjMi05NjA2LWIyMzM5ODZmNjA4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTAyNDVmMDdhNDgyZTM1NDI4NjM3NTgyMDE4OGNlYzk0MGY3Nzk2ZmFlOTY2ZDM2ZGE4NTZiZDJmNDM4MGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Can_2v2KkEYi-l9lfbtufGcAmdVoYGv36i469tZDeKY)

well we handle less because we pushed less of them ?

**Comment by resinate** [comment]
yea i noticed in ur guys list for destructibles, u only do windows and fences, i made nearly every object in mine destructible
plus all lootables.
and item spawns, since i use mix of BR and JS tables.
not even counting when u get 100 players building 1000s of objects in bases XD

**Comment by QuentinGruber** [comment]
cool
