### ISSUE TITLE
Add Kevlar and Military Backpack

### ISSUE THREAD

**Issue by SMOKEYE0512** [QuentinGruber/h1z1-server#2213]
### Would it be possible to:

* Create a vehicle repair kit that will replace wrenchs
* To add a kevlar and military backpack spawn to ranchito because there are some in PV and Cramberry it would be nice to have the possibility to have them in the 3 big cities
* Set a group limit of 8-10 bcs some groups are 15-16 players 
* Bring up the idea of ​​having to put water on the plantations in order to make the seeds grow which will make the plantation system more realistic
* If possible add a sickle to harvest the plantations

**Comment by Z1Meme** [comment]
- No
- Yes
- No
- No
- No

This project aims to emulate the original game's experience as closely as possible, and most of your changes don't really have any good reason for them other than the group limit which is handled differently per-server, and on main servers we don't have a group limit just like the original game.
