### ISSUE TITLE
His Regards Machete BUG

### ISSUE THREAD

**Issue by zxywandxb111** [QuentinGruber/h1z1-server#2266]
The machete has normal damage, the number of attacks on the wooden box is also correct, His Regards Machete's damage and the number of on the wooden box are obviously wrong, the katana is the same.

**Comment by QuentinGruber** [comment]
@zxywandxb111 could you provide the correct damages ?

**Comment by zxywandxb111** [comment]
[https://www.flexclip.com/cn/share/77387875fd23bdb2ec16f7666006505ab8dadf8.html](url)

**Comment by QuentinGruber** [comment]
> https://www.flexclip.com/cn/share/77387875fd23bdb2ec16f7666006505ab8dadf8.html

kk will be done
