### ISSUE TITLE
missing files on local server v41.0

### ISSUE THREAD

**Issue by resinate** [QuentinGruber/h1z1-server#2271]
![image](https://github.com/user-attachments/assets/40459697-69cc-4605-b069-12a675f402e2)

**Comment by resinate** [comment]
this is full clean install of the server client and save world, was checking out v41

**Comment by QuentinGruber** [comment]
Stop creating non-issue plz we do not support node18 since more than a year just update it

**Comment by resinate** [comment]
why doesnt ur installer install proper nodeJS?

**Comment by resinate** [comment]
your main page says nothing about updating node JS or how to btw and i installed nodeJS 23, and ur server still only starts at node 18

**Comment by resinate** [comment]
![image](https://github.com/user-attachments/assets/0c625e33-d7bf-46bc-b43f-f5e35e9b25ac)
