### ISSUE TITLE
server not using correct nodeJS version

### ISSUE THREAD

**Issue by resinate** [QuentinGruber/h1z1-server#2273]
![image](https://github.com/user-attachments/assets/bdbcebb4-b3d5-47d7-a64f-09ac14a753ce)

server is pulling node 18???
![393310438-40459697-69cc-4605-b069-12a675f402e2](https://github.com/user-attachments/assets/1706d7c5-2508-4941-a73c-3d5fa136441f)

theres nothing in main page about updating or installing nodeJS

**Comment by resinate** [comment]
you guys should post to ppl that use launcher that auto update on it isnt working keeps reverting to old version. the nodeJS is from launcher.

**Comment by jasonmoonen** [comment]
Don't expect help if you talk shit like this. Go back where you came from. Best of luck.

We have plenty more of this.

![image](https://github.com/user-attachments/assets/ab17380e-4fdb-4a3b-b878-7e54dc542874)

![image](https://github.com/user-attachments/assets/313561ea-b47a-4ce8-8265-ccbf2741f20d)
