### ISSUE TITLE
find a way to despawn the default spawned objects or make default world objects give an interactionString / playerSelect

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#276]
DespawnNpc packet with objectId from zone file?

**Comment by QuentinGruber** [comment]
maybe it's not even possible

**Comment by QuentinGruber** [comment]
@avcio9 about this, we should try somehow to use terrainIds in npc packets , maybe that's why there is this "failed to spawn" error sometimes

**Comment by avcio9** [comment]
> @avcio9 about this, we should try somehow to use terrainIds in npc packets , maybe that's why there is this "failed to spawn" error sometimes

We are already doing it, their models are changed to empty

**Comment by QuentinGruber** [comment]
also this could be interesting to check facility packets for this

**Comment by QuentinGruber** [comment]
already done by @avcio9 here : https://github.com/QuentinGruber/h1z1-server/blob/dev/src/servers/ZoneServer/zoneserver.ts#L2046
