### ISSUE TITLE
Initialize connection(s) between the login server and zone server(s)

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#314]
Needed for character creation / login security reasons

**Comment by QuentinGruber** [comment]
Maybe using mongodb as the middleman for this then we can skip the communication part. Or using custom udp packets / websockets

**Comment by Z1Meme** [comment]
> 
> 
> Maybe using mongodb as the middleman for this then we can skip the communication part. Or using custom udp packets / websockets

It's a bad idea to use mongodb as a middleman because then the login/zone servers will have to be running on the same pc, meaning we won't be able to have a central h1emu login servers and allow people to put up their own zone servers

**Comment by Z1Meme** [comment]
Custom udp packets are the best move

**Comment by QuentinGruber** [comment]
> > Maybe using mongodb as the middleman for this then we can skip the communication part. Or using custom udp packets / websockets
> 
> It's a bad idea to use mongodb as a middleman because then the login/zone servers will have to be running on the same pc, meaning we won't be able to have a central h1emu login server and allow people to put up their own zone servers

mongodb is already running on another pc on the test server. see https://www.mongodb.com/cloud/atlas

**Comment by QuentinGruber** [comment]
> Custom udp packets are the best move

true we can make an "h1emu protocol" or something

**Comment by QuentinGruber** [comment]
We should list there the custom packets we need and there schemas here @Z1Meme .
Like
```
 [
    "LoginQueueStatusRequest",
    0x11,
    {
      fields: [{ name: "characterId", type: "uint64" }],
    },
  ],
 [
    "LoginQueueStatusReply",
    0x12,
    {
      fields: [{ name: "position", type: "uint32" }],
    },
  ],
```

**Comment by Z1Meme** [comment]
Todo:
- ZoneServer needs to open a connection to login server on zoneserver startup
- LoginServer needs to reply to the zoneserver's connection request
- ZoneServers connections should be stored in an array on the loginserver, since multiple zoneservers should be able to interact with

**Comment by Z1Meme** [comment]
> 
> 
> We should list there the custom packets we need and there schemas here @Z1Meme .
> Like
> 
> ```
>  [
>     "LoginQueueStatusRequest",
>     0x11,
>     {
>       fields: [{ name: "characterId", type: "uint64" }],
>     },
>   ],
>  [
>     "LoginQueueStatusReply",
>     0x12,
>     {
>       fields: [{ name: "position", type: "uint32" }],
>     },
>   ],
> ```

Packet List:
0x1 LoginRequest (ZoneServer->LoginServer)
0x2 LoginReply (LoginServer->ZoneServer)
0x3 Ping (LoginServer->ZoneServer)
(these next 2 packets could be combined maybe to TunnelAppPacketServerToServer)
0x4 TunnelAppPacketZoneToLogin (ZoneServer->LoginServer) 
0x5 TunnelAppPacketLoginToZone (LoginServer->ZoneServer)

**Comment by QuentinGruber** [comment]
Why do you want to have tunnelPackets ? @Z1Meme 

This is an extra complexity that i don't think we need

**Comment by Z1Meme** [comment]
> 
> 
> Why do you want to have tunnelPackets ? @Z1Meme
> 
> This is an extra complexity that i don't think we need

Tunnel packets would be used for packets that go directly to the client, ex. LoginRequest/Reply has nothing to do with the client, it's just between the zone/login servers so it gets it's own packet. NameValidation however gets sent from the client, to the loginserver, to the zone server, and back through that route, and is only meant for one single client, so I think I'd be best to utilize the already established tunnelPacket schemas for data that goes to/from a specific client.

**Comment by Z1Meme** [comment]
It doesn't have to be done that way, but I just thought that i'd be a good way of doing it.

**Comment by QuentinGruber** [comment]
on /dev
