### ISSUE TITLE
Invisible character in third-person

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#315]
Can be temporarily fixed by doing this: https://gyazo.com/b17511ec36d1007f57a4f800fe1f3881

Needs permanent fix.

**Comment by QuentinGruber** [comment]
@Z1Meme have you tried to "activateProfile"? Since i know there is some camera stuff linked to used profile

**Comment by Z1Meme** [comment]
@QuentinGruber I started working on this, however it's a big task.

**Comment by Z1Meme** [comment]
> 
> 
> @Z1Meme have you tried to "activateProfile"? Since i know there is some camera stuff linked to used profile

done, did not fix the issue

**Comment by QuentinGruber** [comment]
do we consider this as "fixed" since it can still happen ? @Z1Meme

**Comment by QuentinGruber** [comment]
oh something fix it in the patch too ? without the patch it wasn't working well
