### ISSUE TITLE
G99 Game error. Game is trying to connect to the server database

### ISSUE THREAD

**Issue by Mast3rcoop** [QuentinGruber/h1z1-server#32]
**Describe the bug**
when i start the game it loads up and then kicks me out and opens the h1z1 website and says the server is down

**Comment by QuentinGruber** [comment]
that mean that your loginsever isn't running or the game don't know his address.

please verify that you've done this step right:

"""
Setup ClientConfig.ini
On the H1Z1 game folder there is a file name "ClientConfig.ini".

Add sessionid=0 at the beginning of this file.

And change the Server value to the adress of your server , probably localhost:PORT
"""

if you haven't change anything the port i use for the loginserver is 1115.

**Comment by Mast3rcoop** [comment]
![Capture](https://user-images.githubusercontent.com/73813359/97902780-ab3de600-1d03-11eb-8125-8717bf32623e.PNG)

still doesnt work

**Comment by QuentinGruber** [comment]
your clientconfig seems right. Are you sure you have a Login Server running ? @Mast3rcoop

**Comment by Mast3rcoop** [comment]
thats why then whoops

**Comment by Mast3rcoop** [comment]
ive gotten into the game but when i try to join my own hosted server i just get kicked off and the game closes so idek
