### ISSUE TITLE
Keep losing blood even after using a medical kit

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#715]
reported by AZAZ.

**Comment by avcio9** [comment]
There are different tiers of bleeding, normal, severe and so on. Stronger ones require bandage to be used multiple times. I've never encounered this using medkid with ID 78. The bug must be either he means bandage or is using unmapped medical ID

**Comment by QuentinGruber** [comment]
> There are different tiers of bleeding, normal, severe and so on. Stronger ones require bandage to be used multiple times. I've never encounered this using medkid with ID 78. The bug must be either he means bandage or is using unmapped medical ID

here is a vid of it https://www.youtube.com/watch?v=twVJgeXbmYM

**Comment by avcio9** [comment]
he is dehydrated xD

**Comment by QuentinGruber** [comment]
> he is dehydrated xD

LMAO didn't saw that
