### ISSUE TITLE
Unable to enter the game

### ISSUE THREAD

**Issue by alvazhang79** [QuentinGruber/h1z1-server#72]
**Describe the bug**
After joining the local server, you cannot enter the game. The h1z1 program is closed.

**To Reproduce**
1. Update the server to 0.7.5 (0.7.4 is the same problem), and start the solo server,
2. Click on 'Launch H1Z1.exe'
3. Join the local server, select the local player, and click play
4. H1z1 game disappeared

The debugging information of solo server stays at:
ZoneServer Client logged in from 127.0.0.1:58252 with character id 0x03147cca2a860191 +28s
  ZoneServer zone login +1ms
  ZoneServer send data InitializationParameters +3ms
  ZoneServer send data SendZoneDetails +5ms
  ZoneServer send data ClientUpdate.ZonePopulation +2ms
  ZoneServer send data ClientUpdate.RespawnLocations +2ms
  ZoneServer send data ClientGameSettings +3ms
  ZoneServer send data SendSelfToClient +4ms
  ZoneServer send data PlayerUpdate.SetBattleRank +3ms

**Comment by QuentinGruber** [comment]
Hi @alvazhang79  download the lastest version of h1emu app and press "apply patch" https://github.com/H1emu/H1emu-server-app/releases/tag/v1.1.1

**Comment by alvazhang79** [comment]
> Hi @alvazhang79 download the lastest version of h1emu app and press "apply patch" https://github.com/H1emu/H1emu-server-app/releases/tag/v1.1.1

Thank you. I'm ready to play.
But the character moves very slowly, and only walks, not runs.

**Comment by QuentinGruber** [comment]
Yep for now the movement speed isn't working , you can still use `/hax run 15` to have a little more speed or `/hax run -500` to become sonic but by pressing the 'S' key to go forward.
