### ISSUE TITLE
Overhaul loot spawning system

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#751]
Item spawns should use a weight system to determine which items should spawn more frequently than another, and a better randomization agorithm should be used to hopefully prevent too much loot stacking up in certain areas, and very little in others.

**Comment by Z1Meme** [comment]
Loot system should also use a "spawns.json" file which determines the spawnrates for everything, this way servers can easily modify / overwrite this file to have custom spawns.

**Comment by QuentinGruber** [comment]
#1127
