### ISSUE TITLE
Driving through a zombie should kill it

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#754]
Use isPosInRadius for now to detect when a vehicle impacts a zombie, and kill it.

**Comment by QuentinGruber** [comment]
To me it doesn't seem worth it, it would consume a lot of resources to check if an npc is within the radius of a moving vehicle at each new positionUpdate; maybe we should wait for that or find a better solution.

**Comment by QuentinGruber** [comment]
I could test that with only spawned entities, maybe that will not eat the CPU we will see
