### ISSUE TITLE
Player seems to not take fall damage

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#756]
**Describe the bug**
Player seems to not take fall damage

**To Reproduce**
1. Jump from the montain
2. Survive

**Comment by Z1Meme** [comment]
This is a clientside issue and happened often when the game was online.

**Comment by QuentinGruber** [comment]
> This is a clientside issue and happened often when the game was online.

oh ok didn't know that will leave that as a "wontfix" then.
