### ISSUE TITLE
Send client items definition 

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#76]
Via the "Command.ItemDefinitions" packet
This is maybe blocking us on #62 
[Command.ItemDefinitions.zip](https://github.com/QuentinGruber/h1z1-server/files/5653360/Command.ItemDefinitions.zip)
This packet is a working one from ps2 , my work will be based on.

**Comment by Z1Meme** [comment]
Not fixed yet, this is the next step in getting the inventory / items working

**Comment by QuentinGruber** [comment]
as this is done in 2016 , i let this open until it's done on 2015 too

**Comment by QuentinGruber** [comment]
used compression : https://github.com/richgel999/lzham_codec if ever
