### ISSUE TITLE
Fix dam spawn location

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#763]
Dam spawn location for 2016 spawns you inside a rock

**Comment by QuentinGruber** [comment]
also "basic h1emu spawn" make you spawn in the air, should change the Y value to match the current one used on the 2015 server

**Comment by QuentinGruber** [comment]
![image](https://user-images.githubusercontent.com/47059878/161264617-bd01f71c-fe88-4e6f-988e-a386583d4c76.png)
it seems it didn't have been fixed

**Comment by QuentinGruber** [comment]
and the linked PR doesn't include commits to fix that
