### ISSUE TITLE
Change error url to h1emu.com

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#768]

**Comment by QuentinGruber** [comment]
@Z1Meme closed by mistake or you're against this ?

**Comment by Z1Meme** [comment]
> @Z1Meme closed by mistake or you're against this ?

LOL my bad I was removing issues we fixed this update and I deleted this by mistake. I think it's a great idea btw.

**Comment by QuentinGruber** [comment]
idk how to modify it via command line or if it's even possible since it's a nested parameter.

**Comment by QuentinGruber** [comment]
done in https://github.com/H1emu/h1emu-launcher/commit/073359b99dd516c945ed5d5322768bb3fc9ea7f6
