### ISSUE TITLE
H1z1-loginserver not able to establish connection with H1z1-Zoneserver

### ISSUE THREAD

**Issue by 1arrcy1** [QuentinGruber/h1z1-server#777]
**Describe the bug**
Crashing of h1z1 client when trying to connect to the server. This is probably caused by zone and login server not able to communicate. 
Same behaviour with docker. Also with docker will the client crash when trying to join

**To Reproduce**
docker:
1. `docker run -d -it --restart always --env LOGINSERVER_IP="127.0.0.1" --env MONGO_URL="mongodb://127.0.0.1:27017" --env WORLD_ID=2 --env DEBUG --net=host -d h1emu/server-2016:latest`
2. `docker run -it --restart always -d --name mongo --network host -v /datastore/DockerData/h1z1/mongo/configdb:/data/configdb -v /datastore/DockerData/h1z1/mongo/db:/data/db -v /datastore/DockerData/h1z1/mongo/backup:/data/backup mongo:4.4.13`
3.  use h1emu launcher to get into the server overview
4. click join then crashes game + spits out logs below

Linode/cloud:
1. run install server script made by me https://github.com/1arrcy1/H1z1-server-install-script
2. check if server is running with pm2 logs, which works
3.  use h1emu launcher to get into the server overview
4. click join then crashes game + spits out logs below

**Expected behavior**
Use linode or docker to get a server up.
being able to click join server without having your game crash

**Additional context**
[error-docker.log](https://github.com/QuentinGruber/h1z1-server/files/8393749/error-docker.log)
[error-cloud.txt](https://github.com/QuentinGruber/h1z1-server/files/8393750/error-cloud.txt)

**Comment by QuentinGruber** [comment]
Hey @1arrcy1 thx for opening this issue, but it's most likely that the loginserver send a wrong zone ip to connect to the client or that your gamepatch isn't up to date but it really seems to be the first case :) will look at that

**Comment by 1arrcy1** [comment]
Hello @QuentinGruber thx for reviewing this issue,
I made a small vid showing that its not client side or because of a wrong game patch. It must be something with the 2 servers having issues connecting with each other.
https://www.youtube.com/watch?v=xns3Vs0NJqs

**Comment by QuentinGruber** [comment]
> Hello @QuentinGruber thx for reviewing this issue, I made a small vid showing the problem https://www.youtube.com/watch?v=xns3Vs0NJqs
> 
> Also do you know where i can find all the envirement variable's, so it's easier to change server settings.
> 
> Much thx for making this project possible :p

About all env variables a list will be added soon : https://github.com/QuentinGruber/h1z1-server/issues/776 , but rn you can do a quick search on the source code with this pattern : `process.env.SOMETHING`

**Comment by 1arrcy1** [comment]
Got it working, for those having trouble https://github.com/1arrcy1/H1z1-server-install-script
makes the proces automated
