### ISSUE TITLE
groupPackets

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#790]

**Comment by QuentinGruber** [comment]
maybe useless since there are already grouped packets ( at the app level ) on h1z1 like for weapons

**Comment by Z1Meme** [comment]
@QuentinGruber Is this issue dead?

**Comment by QuentinGruber** [comment]
Not really @Z1Meme i can still do it, i just don't know how to add that to our codebase in a cool and easy way to use. Btw z1br doesn't seems to use this type of internal packet so idk if it will perform well or not (even tho it should)

**Comment by QuentinGruber** [comment]
After several tests, it seems that this feature is not really implemented in the game or works badly. If one day this feature is required to solve performance issues then I would look into it again. ( Daybreak does not use it on its live games )
