### ISSUE TITLE
Adding more players

### ISSUE THREAD

**Issue by NukedBart** [QuentinGruber/h1z1-server#86]
**Is your feature request related to a problem? Please describe.**

Seems like the server is only connecting 1 client, I'm always frustrated when I'm trying to play with others in lan and failed on it.

**Describe the solution you'd like**

Allowing more people to join one server.

**Describe alternatives you've considered**

Use mongodb to store data.

**Additional context**

Close this issue if not supporting this.

**Comment by QuentinGruber** [comment]
still a thing to do ( good progress with spawning a PCcontroller )
