### ISSUE TITLE
I can't download 2016

### ISSUE THREAD

**Issue by CasterZhen** [QuentinGruber/h1z1-server#870]
**Describe the bug**

**To Reproduce**
![1652872407543](https://user-images.githubusercontent.com/105789371/169035483-0e93872b-f16a-4a45-b6c1-27138150e336.jpg)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by QuentinGruber** [comment]
Hey @CasterZhen wrong repository, create issues for the launcher on https://github.com/H1emu/h1emu-launcher , I'm transferring it rn.

**Comment by QuentinGruber** [comment]
Oh i just saw that you've already create one on the right repo thx !
