### ISSUE TITLE
Press R while playing will cause a crash.

### ISSUE THREAD

**Issue by NukedBart** [QuentinGruber/h1z1-server#88]
**Describe the bug**

Playing pressing R boom.

**To Reproduce**

-
1. Get in
2. Play
3. Press R
4. Game crashes

**Expected behavior**

It shouldn't crash.

**Screenshots**

**Additional context**

**Comment by QuentinGruber** [comment]
Probably linked to #38 , since we send a bad inventory/loadout.

**Comment by QuentinGruber** [comment]
this is still a thing
