### ISSUE TITLE
Cant use the Fire Button

### ISSUE THREAD

**Issue by LicoZGER** [QuentinGruber/h1z1-server#924]
**Describe the bug**
I cant use the fire button so i dont be able to attack oder defend or something. Default are the left mouse and right mouse the setting. But also on other Keys ist the same. Switch from German Layout to English Layout, without a change

**Comment by QuentinGruber** [comment]
Hey, @LicoZGER h1z1-server is still under development, shooting capability is not implemented yet but it has been worked on #875 😄.

**Comment by LicoZGER** [comment]
uuups thank you
