### ISSUE TITLE
ClientBeginZoning fix

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#935]
ClientBeginZoning currently gets sent, but the data doesn't seem to be doing anything since the structure is missing a byte. Sending that byte however causes the client to "boot-loop", loading the zone over and over again. WaitForWorldReady patch can probably be removed once this is fixed.

**Comment by QuentinGruber** [comment]
Well if it's a wontfix, we should close it right ? @Z1Meme

**Comment by Z1Meme** [comment]
> Well if it's a wontfix, we should close it right ? @Z1Meme

yep
