### ISSUE TITLE
Fix blackberry pickups serverside

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#986]
Blackberry pickups were broken in the weapon's update due to the "InitializationParameters" packet being sent correctly now. It's missing some data which enables blackberry pickups. (Also disables loading screen messages)

**Comment by QuentinGruber** [comment]
JS.environement

**Comment by avcio9** [comment]
Will be fixed on next patch

**Comment by QuentinGruber** [comment]
Maybe we should keep this issue open as it is not really fixed on the server side?

**Comment by Z1Meme** [comment]
> Maybe we should keep this issue open as it is not really fixed on the server side?

I'll change the issue name, good idea.
