### ISSUE TITLE
Gen serverinfo string from new fields in the servers collection

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#992]
- [ ] rulesets
- [ ] region

**Comment by Z1Meme** [comment]
need to find a good XML parse/pack library for this since that's the format that data is in

**Comment by QuentinGruber** [comment]
> need to find a good XML parse/pack library for this since that's the format that data is in

Well the XML format isn't that complexe we could write something ourself.

**Comment by QuentinGruber** [comment]
I've an other plan
